"""Launchd service management for Dopemux global services."""

from __future__ import annotations

import logging
import os
import plistlib
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import yaml

from dopemux.routing_config import RoutingConfig

logger = logging.getLogger(__name__)


class LaunchdServiceError(RuntimeError):
    """Raised when launchd service operations fail."""


class LaunchdServiceManager:
    """Manage launchd services for Dopemux global infrastructure."""

    DOPEMUX_DIR = Path.home() / ".dopemux"
    SCRIPTS_DIR = DOPEMUX_DIR / "scripts"
    LITELLM_DIR = DOPEMUX_DIR / "litellm"
    CCR_DIR = DOPEMUX_DIR / "ccr"
    LOGS_DIR = DOPEMUX_DIR / "logs"
    LAUNCHAGENTS_DIR = Path.home() / "Library" / "LaunchAgents"

    LITELLM_SERVICE_NAME = "com.dopemux.litellm"
    CCR_SERVICE_NAME = "com.dopemux.ccr"

    def __init__(self):
        """Initialize the launchd service manager."""
        self.routing_config = RoutingConfig()
        self._ensure_directories()

    def _ensure_directories(self) -> None:
        """Ensure all required directories exist."""
        directories = [
            self.DOPEMUX_DIR,
            self.SCRIPTS_DIR,
            self.LITELLM_DIR,
            self.CCR_DIR,
            self.LOGS_DIR,
            self.LAUNCHAGENTS_DIR,
        ]
        
        for directory in directories:
            directory.mkdir(parents=True, exist_ok=True)
            logger.debug(f"Ensured directory: {directory}")

    def _generate_routing_env(self) -> None:
        """Generate ~/.dopemux/routing.env with environment variables."""
        env_path = self.DOPEMUX_DIR / "routing.env"
        
        # Load routing config to get provider info
        config = self.routing_config.load()
        providers = config.get("providers", [])
        
        # Generate environment variables for each provider
        env_vars = {
            "DOPEMUX_LITELLM_MASTER_KEY": self._generate_secure_key("litellm_master"),
            "DOPEMUX_CCR_API_KEY": self._generate_secure_key("ccr_api"),
            "DOPEMUX_ROUTING_MODE": config.get("mode", "subscription"),
        }
        
        # Add ports
        ports = config.get("ports", {})
        env_vars["DOPEMUX_LITELLM_PORT"] = str(ports.get("litellm", 4000))
        env_vars["DOPEMUX_CCR_PORT"] = str(ports.get("ccr", 4010))
        
        # Write to file
        with open(env_path, "w") as f:
            f.write("# Dopemux Routing Environment Variables\n")
            f.write("# Generated by dopemux launchd services\n")
            f.write("# Run 'dopemux routing sync-keys' to sync API keys from your environment\n\n")
            
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")
        
        logger.info(f"Generated routing environment file: {env_path}")

    def sync_keys_from_environment(self) -> None:
        """Sync API keys from current environment to routing.env."""
        env_path = self.DOPEMUX_DIR / "routing.env"
        
        # Load existing env file
        existing_vars = {}
        if env_path.exists():
            with open(env_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        existing_vars[key] = value
        
        # Provider API keys to sync from environment
        provider_keys = [
            "XAI_API_KEY",
            "OPENROUTER_API_KEY",
            "OPENAI_API_KEY",
            "GEMINI_API_KEY",
            "DEEPSEEK_API_KEY",
        ]
        
        # Update with values from current environment if present
        for key in provider_keys:
            if key in os.environ and os.environ[key]:
                existing_vars[key] = os.environ[key]
        
        # Write updated file
        with open(env_path, "w") as f:
            f.write("# Dopemux Routing Environment Variables\n")
            f.write("# Generated by dopemux launchd services\n")
            f.write("# Keys synced from current environment\n\n")
            
            for key, value in existing_vars.items():
                f.write(f"{key}={value}\n")
        
        logger.info(f"Synced API keys to routing environment file: {env_path}")

    def _generate_secure_key(self, prefix: str) -> str:
        """Generate a secure random key for internal services."""
        import secrets
        import string
        
        alphabet = string.ascii_letters + string.digits
        return f"dopemux_{prefix}_{secrets.token_urlsafe(16)}"

    def _generate_litellm_wrapper_script(self) -> None:
        """Generate wrapper script for LiteLLM service."""
        script_path = self.SCRIPTS_DIR / "litellm_wrapper.sh"
        
        # Resolve binary paths at install time
        litellm_bin = shutil.which("litellm")
        if not litellm_bin:
            raise LaunchdServiceError(
                "LiteLLM binary not found in PATH. "
                "Please install LiteLLM: pip install litellm[proxy]"
            )
        
        home_dir = str(Path.home())
        script_content = f"""#!/bin/bash
# Dopemux LiteLLM Wrapper Script
# Generated by dopemux launchd services

set -eo pipefail

# Load environment variables
if [ -f "{home_dir}/.dopemux/routing.env" ]; then
    source "{home_dir}/.dopemux/routing.env"
fi

# Set default values if not set
LITELLM_PORT=${{DOPEMUX_LITELLM_PORT:-4000}}
LITELLM_MASTER_KEY=${{DOPEMUX_LITELLM_MASTER_KEY:-""}}

if [ -z "$LITELLM_MASTER_KEY" ]; then
    echo "❌ Error: DOPEMUX_LITELLM_MASTER_KEY not set in routing.env"
    echo "Run: dopemux routing sync-keys to sync API keys from your environment"
    exit 1
fi

# Set up logging
LOG_DIR="{home_dir}/.dopemux/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/litellm_$(date +%Y%m%d_%H%M%S).log"

echo "🚀 Starting LiteLLM on port $LITELLM_PORT..."
echo "📝 Logging to: $LOG_FILE"

# Start LiteLLM directly (no docker)
exec "{litellm_bin}" --config "{home_dir}/.dopemux/litellm/litellm.config.yaml" \\
    --port "$LITELLM_PORT" \\
    --host 0.0.0.0 \\
    >> "$LOG_FILE" 2>&1
"""
        
        with open(script_path, "w") as f:
            f.write(script_content)
        
        # Make executable
        script_path.chmod(0o755)
        logger.info(f"Generated LiteLLM wrapper script: {script_path}")

    def _generate_ccr_wrapper_script(self) -> None:
        """Generate wrapper script for CCR service."""
        script_path = self.SCRIPTS_DIR / "ccr_wrapper.sh"
        
        # Resolve binary paths at install time
        ccr_bin = shutil.which("ccr")
        if not ccr_bin:
            raise LaunchdServiceError(
                "CCR binary not found in PATH. "
                "Please install CCR or ensure it's in your PATH"
            )
        
        home_dir = str(Path.home())
        script_content = f"""#!/bin/bash
# Dopemux CCR Wrapper Script
# Generated by dopemux launchd services

set -eo pipefail

# Load environment variables
if [ -f "{home_dir}/.dopemux/routing.env" ]; then
    source "{home_dir}/.dopemux/routing.env"
fi

# Set default values if not set
CCR_PORT=${{DOPEMUX_CCR_PORT:-4010}}
LITELLM_URL="http://localhost:${{DOPEMUX_LITELLM_PORT:-4000}}"
CCR_API_KEY=${{DOPEMUX_CCR_API_KEY:-""}}

if [ -z "$CCR_API_KEY" ]; then
    echo "❌ Error: DOPEMUX_CCR_API_KEY not set in routing.env"
    echo "Run: dopemux routing sync-keys to sync API keys from your environment"
    exit 1
fi

# Set up logging
LOG_DIR="{home_dir}/.dopemux/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/ccr_$(date +%Y%m%d_%H%M%S).log"

echo "🚀 Starting CCR on port $CCR_PORT..."
echo "📝 Logging to: $LOG_FILE"

# Start CCR directly (no docker)
exec "{ccr_bin}" --config "{home_dir}/.dopemux/ccr/config.json" \\
    --port "$CCR_PORT" \\
    --litellm-url "$LITELLM_URL" \\
    --litellm-key "$DOPEMUX_LITELLM_MASTER_KEY" \\
    >> "$LOG_FILE" 2>&1
"""
        
        with open(script_path, "w") as f:
            f.write(script_content)
        
        # Make executable
        script_path.chmod(0o755)
        logger.info(f"Generated CCR wrapper script: {script_path}")

    def _generate_litellm_config(self) -> None:
        """Generate LiteLLM configuration from routing config."""
        config_path = self.LITELLM_DIR / "litellm.config.yaml"
        
        # Load routing config
        routing_config = self.routing_config.load()
        
        # Generate LiteLLM config
        litellm_config = self.routing_config.generate_litellm_config(
            master_key="${DOPEMUX_LITELLM_MASTER_KEY}"
        )
        
        # Write to file
        with open(config_path, "w") as f:
            yaml.dump(litellm_config, f, sort_keys=False)
        
        logger.info(f"Generated LiteLLM config: {config_path}")

    def _generate_ccr_config(self) -> None:
        """Generate CCR configuration from routing config."""
        config_path = self.CCR_DIR / "config.json"
        
        # Load routing config
        routing_config = self.routing_config.load()
        ports = routing_config.get("ports", {})
        
        # Generate CCR config
        ccr_config = self.routing_config.generate_ccr_config(
            litellm_url="http://localhost:${DOPEMUX_LITELLM_PORT:-4000}",
            litellm_key="${DOPEMUX_LITELLM_MASTER_KEY}",
            ccr_api_key="${DOPEMUX_CCR_API_KEY}"
        )
        
        # Write to file
        with open(config_path, "w") as f:
            import json
            json.dump(ccr_config, f, indent=2)
        
        logger.info(f"Generated CCR config: {config_path}")

    def _generate_litellm_plist(self) -> None:
        """Generate launchd plist for LiteLLM service."""
        plist_path = self.LAUNCHAGENTS_DIR / f"{self.LITELLM_SERVICE_NAME}.plist"
        
        home_dir = str(Path.home())
        plist_content = {
            "Label": self.LITELLM_SERVICE_NAME,
            "ProgramArguments": [
                "bash",
                "-c",
                f"source {home_dir}/.dopemux/routing.env && {self.SCRIPTS_DIR}/litellm_wrapper.sh"
            ],
            "RunAtLoad": True,
            "KeepAlive": True,
            "StandardErrorPath": str(self.LOGS_DIR / "litellm_launchd.log"),
            "StandardOutPath": str(self.LOGS_DIR / "litellm_launchd.log"),
            "EnvironmentVariables": {
                "PATH": "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
                "HOME": home_dir,
            },
            "WorkingDirectory": str(self.DOPEMUX_DIR),
        }
        
        # Write plist
        with open(plist_path, "wb") as f:
            plistlib.dump(plist_content, f)
        
        logger.info(f"Generated LiteLLM plist: {plist_path}")

    def _generate_ccr_plist(self) -> None:
        """Generate launchd plist for CCR service."""
        plist_path = self.LAUNCHAGENTS_DIR / f"{self.CCR_SERVICE_NAME}.plist"
        
        home_dir = str(Path.home())
        plist_content = {
            "Label": self.CCR_SERVICE_NAME,
            "ProgramArguments": [
                "bash",
                "-c",
                f"source {home_dir}/.dopemux/routing.env && {self.SCRIPTS_DIR}/ccr_wrapper.sh"
            ],
            "RunAtLoad": True,
            "KeepAlive": True,
            "StandardErrorPath": str(self.LOGS_DIR / "ccr_launchd.log"),
            "StandardOutPath": str(self.LOGS_DIR / "ccr_launchd.log"),
            "EnvironmentVariables": {
                "PATH": "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
                "HOME": home_dir,
            },
            "WorkingDirectory": str(self.DOPEMUX_DIR),
        }
        
        # Write plist
        with open(plist_path, "wb") as f:
            plistlib.dump(plist_content, f)
        
        logger.info(f"Generated CCR plist: {plist_path}")

    def install_services(self) -> None:
        """Install all launchd services."""
        logger.info("🛠️  Installing Dopemux launchd services...")
        
        # Generate all configuration files
        self._generate_routing_env()
        self._generate_litellm_wrapper_script()
        self._generate_ccr_wrapper_script()
        self._generate_litellm_config()
        self._generate_ccr_config()
        self._generate_litellm_plist()
        self._generate_ccr_plist()
        
        # Load services with launchctl
        self._load_service(self.LITELLM_SERVICE_NAME)
        self._load_service(self.CCR_SERVICE_NAME)
        
        logger.info("✅ Dopemux launchd services installed successfully!")

    def _load_service(self, service_name: str) -> None:
        """Load a launchd service using bootstrap."""
        plist_path = self.LAUNCHAGENTS_DIR / f"{service_name}.plist"
        
        if not plist_path.exists():
            raise LaunchdServiceError(f"Plist not found: {plist_path}")
        
        # Unload if already loaded
        self._unload_service(service_name)
        
        # Load the service using bootstrap
        uid = os.getuid()
        try:
            subprocess.run(
                ["launchctl", "bootstrap", f"gui/{uid}", str(plist_path)],
                check=True
            )
            logger.info(f"✅ Loaded service: {service_name}")
        except subprocess.CalledProcessError as e:
            raise LaunchdServiceError(f"Failed to load service {service_name}: {e}") from e

    def _unload_service(self, service_name: str) -> None:
        """Unload a launchd service using bootout."""
        plist_path = self.LAUNCHAGENTS_DIR / f"{service_name}.plist"
        
        uid = os.getuid()
        try:
            subprocess.run(
                ["launchctl", "bootout", f"gui/{uid}", str(plist_path)],
                check=False
            )
            logger.info(f"🔄 Unloaded service: {service_name}")
        except Exception as e:
            logger.warning(f"Warning: Failed to unload service {service_name}: {e}")

    def start_services(self) -> None:
        """Start all launchd services."""
        logger.info("🚀 Starting Dopemux launchd services...")
        
        self._start_service(self.LITELLM_SERVICE_NAME)
        self._start_service(self.CCR_SERVICE_NAME)
        
        logger.info("✅ Dopemux launchd services started!")

    def _start_service(self, service_name: str) -> None:
        """Start a launchd service."""
        try:
            subprocess.run(["launchctl", "start", service_name], check=True)
            logger.info(f"✅ Started service: {service_name}")
        except subprocess.CalledProcessError as e:
            raise LaunchdServiceError(f"Failed to start service {service_name}: {e}") from e

    def stop_services(self) -> None:
        """Stop all launchd services."""
        logger.info("⏹️  Stopping Dopemux launchd services...")
        
        self._stop_service(self.LITELLM_SERVICE_NAME)
        self._stop_service(self.CCR_SERVICE_NAME)
        
        logger.info("✅ Dopemux launchd services stopped!")

    def _stop_service(self, service_name: str) -> None:
        """Stop a launchd service."""
        try:
            subprocess.run(["launchctl", "stop", service_name], check=False)
            logger.info(f"✅ Stopped service: {service_name}")
        except Exception as e:
            logger.warning(f"Warning: Failed to stop service {service_name}: {e}")

    def reload_services(self) -> None:
        """Reload all launchd services (unload + load)."""
        logger.info("🔄 Reloading Dopemux launchd services...")
        
        self._reload_service(self.LITELLM_SERVICE_NAME)
        self._reload_service(self.CCR_SERVICE_NAME)
        
        logger.info("✅ Dopemux launchd services reloaded!")

    def _reload_service(self, service_name: str) -> None:
        """Reload a launchd service."""
        self._unload_service(service_name)
        self._load_service(service_name)
        self._start_service(service_name)

    def uninstall_services(self) -> None:
        """Uninstall all launchd services."""
        logger.info("🗑️  Uninstalling Dopemux launchd services...")
        
        self._uninstall_service(self.LITELLM_SERVICE_NAME)
        self._uninstall_service(self.CCR_SERVICE_NAME)
        
        # Clean up configuration files
        self._cleanup_config_files()
        
        logger.info("✅ Dopemux launchd services uninstalled!")

    def _uninstall_service(self, service_name: str) -> None:
        """Uninstall a launchd service."""
        self._stop_service(service_name)
        self._unload_service(service_name)
        
        # Remove plist file
        plist_path = self.LAUNCHAGENTS_DIR / f"{service_name}.plist"
        if plist_path.exists():
            plist_path.unlink()
            logger.info(f"🗑️  Removed plist: {plist_path}")

    def _cleanup_config_files(self) -> None:
        """Clean up configuration files."""
        # Remove generated files but keep routing.env (user may have set API keys)
        files_to_clean = [
            self.SCRIPTS_DIR / "litellm_wrapper.sh",
            self.SCRIPTS_DIR / "ccr_wrapper.sh",
            self.LITELLM_DIR / "litellm.config.yaml",
            self.CCR_DIR / "config.json",
        ]
        
        for file_path in files_to_clean:
            if file_path.exists():
                file_path.unlink()
                logger.info(f"🗑️  Removed config file: {file_path}")

    def get_service_status(self) -> Dict[str, Any]:
        """Get status of all launchd services."""
        status = {
            "litellm": self._get_service_status(self.LITELLM_SERVICE_NAME),
            "ccr": self._get_service_status(self.CCR_SERVICE_NAME),
        }
        return status

    def _get_service_status(self, service_name: str) -> Dict[str, Any]:
        """Get status of a single launchd service."""
        try:
            result = subprocess.run(
                ["launchctl", "print", f"gui/{os.getuid()}/{service_name}"],
                capture_output=True,
                text=True,
                check=False
            )
            
            if result.returncode == 0:
                return {
                    "status": "running",
                    "details": result.stdout.strip(),
                }
            else:
                return {
                    "status": "stopped",
                    "details": result.stderr.strip(),
                }
        except Exception as e:
            return {
                "status": "error",
                "details": str(e),
            }

    def kickstart(self, service: Optional[str] = None) -> Dict[str, Any]:
        """Restart services using launchctl kickstart.
        
        Args:
            service: Specific service to kickstart ('litellm', 'ccr'), or None for all
            
        Returns:
            Dictionary with results for each service
        """
        results = {}
        services_to_kick = []
        
        if service is None or service == "litellm":
            services_to_kick.append(self.LITELLM_SERVICE_NAME)
        if service is None or service == "ccr":
            services_to_kick.append(self.CCR_SERVICE_NAME)
        
        for svc_name in services_to_kick:
            try:
                result = subprocess.run(
                    ["launchctl", "kickstart", "-k", f"gui/{os.getuid()}/{svc_name}"],
                    capture_output=True,
                    text=True,
                    check=False
                )
                results[svc_name] = {
                    "ok": result.returncode == 0,
                    "exit_code": result.returncode,
                    "stderr_snippet": result.stderr[:200] if result.stderr else None
                }
                logger.info(f"Kickstarted service {svc_name}: {'ok' if result.returncode == 0 else 'failed'}")
            except Exception as e:
                results[svc_name] = {
                    "ok": False,
                    "exit_code": 1,
                    "stderr_snippet": str(e)[:200]
                }
                logger.error(f"Failed to kickstart service {svc_name}: {e}")
        
        return results
    
    def _regenerate_configs(self) -> None:
        """Regenerate configuration files for both services."""
        logger.info("🔄 Regenerating configuration files...")
        self._generate_litellm_config()
        self._generate_ccr_config()
        logger.info("✅ Configuration files regenerated")
    
    def _get_log_paths(self) -> Dict[str, str]:
        """Get paths to relevant log files for diagnostics.
        
        Returns:
            Dictionary with log file paths (names only, no sensitive content)
        """
        return {
            "litellm_launchd": str(self.LOGS_DIR / "litellm_launchd.log"),
            "ccr_launchd": str(self.LOGS_DIR / "ccr_launchd.log"),
            "litellm_latest": self._get_latest_litellm_log()
        }
    
    def _get_latest_litellm_log(self) -> str:
        """Find the newest LiteLLM log file."""
        try:
            logs = list(self.LOGS_DIR.glob("litellm_*.log"))
            if logs:
                return str(max(logs, key=lambda f: f.stat().st_mtime))
        except Exception:
            pass
        return "N/A (no logs found)"
    
    def repair(self, max_passes: int = 3, allow_sync_keys: bool = False) -> Dict[str, Any]:
        """Attempt to repair routing services through multiple passes.
        
        Args:
            max_passes: Maximum number of repair attempts (default 3)
            allow_sync_keys: Whether to attempt key syncing in pass 3 (default False)
            
        Returns:
            Dictionary with repair results and final health status
        """
        attempts = []
        final_health = {}
        
        # Ensure we have the routing config loaded
        try:
            if not self.routing_config._loaded:
                self.routing_config.load()
        except Exception as e:
            return {
                "healthy": False,
                "attempts": [],
                "health": {
                    "config": {
                        "status": "unhealthy",
                        "error": f"Cannot load routing config: {e}"
                    }
                }
            }
        
        # Pass 1: Kickstart both services
        logger.info("🔧 Repair Pass 1/3: Kickstarting services...")
        pass1_result = self.kickstart()
        attempts.append({
            "pass": 1,
            "action": "kickstart",
            "result": pass1_result
        })
        
        # Check health after pass 1
        health = self.check_health()
        if self._is_healthy(health):
            final_health = health
            logger.info("✅ Services healthy after pass 1")
            return {"healthy": True, "attempts": attempts, "health": final_health}
        
        # Pass 2: Regenerate configs and kickstart
        if max_passes >= 2:
            logger.info("🔧 Repair Pass 2/3: Regenerating configs and kickstarting...")
            self._regenerate_configs()
            pass2_result = self.kickstart()
            attempts.append({
                "pass": 2,
                "action": "regenerate_configs + kickstart",
                "result": pass2_result
            })
            
            # Check health after pass 2
            health = self.check_health()
            if self._is_healthy(health):
                final_health = health
                logger.info("✅ Services healthy after pass 2")
                return {"healthy": True, "attempts": attempts, "health": final_health}
        
        # Pass 3: Sync keys and kickstart (if allowed)
        if max_passes >= 3 and allow_sync_keys:
            logger.info("🔧 Repair Pass 3/3: Syncing keys and kickstarting...")
            try:
                self.sync_keys_from_environment()
                pass3_result = self.kickstart()
                attempts.append({
                    "pass": 3,
                    "action": "sync_keys + kickstart",
                    "result": pass3_result
                })
                
                # Check health after pass 3
                health = self.check_health()
                if self._is_healthy(health):
                    final_health = health
                    logger.info("✅ Services healthy after pass 3")
                    return {"healthy": True, "attempts": attempts, "health": final_health}
            except Exception as e:
                logger.error(f"Pass 3 failed: {e}")
                attempts.append({
                    "pass": 3,
                    "action": "sync_keys + kickstart",
                    "result": {"error": str(e)}
                })
        
        # Final health check
        final_health = self.check_health()
        logger.info("❌ Services still unhealthy after all repair attempts")
        return {"healthy": False, "attempts": attempts, "health": final_health}
    
    def _is_healthy(self, health: Dict[str, Any]) -> bool:
        """Check if health status indicates all services are healthy."""
        if "config" in health and health["config"]["status"] == "unhealthy":
            return False
        
        # In subscription mode, we don't need services running
        try:
            mode = self.routing_config.config.get('mode', 'subscription')
            if mode == 'subscription':
                return True
        except Exception:
            pass
        
        # Check both services are healthy
        litellm_healthy = health.get("litellm", {}).get("status") == "healthy"
        ccr_healthy = health.get("ccr", {}).get("status") == "healthy"
        
        return litellm_healthy and ccr_healthy
    
    def check_health(self) -> Dict[str, Any]:
        """Check health of running services."""
        health = {}
        
        # Ensure config is loaded
        if not self.routing_config._loaded:
            self.routing_config.load()
        
        # In subscription mode, services are not required
        try:
            mode = self.routing_config.config.get('mode', 'subscription')
            if mode == 'subscription':
                health["mode"] = {
                    "status": "healthy",
                    "message": "subscription mode - no services required"
                }
                return health
        except Exception:
            pass
        
        # Check LiteLLM health
        try:
            import requests
            litellm_url = f"http://localhost:{self.routing_config.config['ports']['litellm']}/health/readiness"
            response = requests.get(litellm_url, timeout=5)
            health["litellm"] = {
                "status": "healthy" if response.status_code == 200 else "unhealthy",
                "response": response.text,
            }
        except Exception as e:
            health["litellm"] = {
                "status": "unhealthy",
                "error": str(e),
            }
        
        # Check CCR health
        try:
            ccr_url = f"http://localhost:{self.routing_config.config['ports']['ccr']}/health"
            response = requests.get(ccr_url, timeout=5)
            health["ccr"] = {
                "status": "healthy" if response.status_code == 200 else "unhealthy",
                "response": response.text,
            }
        except Exception as e:
            health["ccr"] = {
                "status": "unhealthy",
                "error": str(e),
            }
        
        return health

    def generate_docker_compose_snippets(self) -> Dict[str, str]:
        """Generate Docker Compose snippets for the services."""
        routing_config = self.routing_config.load()
        ports = routing_config.get("ports", {})
        
        litellm_snippet = f"""
  dopemux-litellm:
    image: dopemux-litellm
    ports:
      - "{ports['litellm']}:4000"
    environment:
      - LITELLM_MASTER_KEY=${{DOPEMUX_LITELLM_MASTER_KEY}}
      - XAI_API_KEY=${{XAI_API_KEY}}
      - OPENROUTER_API_KEY=${{OPENROUTER_API_KEY}}
    volumes:
      - ~/.dopemux/litellm/litellm.config.yaml:/app/config.yaml
    restart: unless-stopped
"""
        
        ccr_snippet = f"""
  dopemux-ccr:
    image: dopemux-ccr
    ports:
      - "{ports['ccr']}:4010"
    environment:
      - DOPEMUX_LITELLM_URL=http://dopemux-litellm:4000
      - DOPEMUX_LITELLM_MASTER_KEY=${{DOPEMUX_LITELLM_MASTER_KEY}}
      - DOPEMUX_CCR_API_KEY=${{DOPEMUX_CCR_API_KEY}}
    volumes:
      - ~/.dopemux/ccr/config.json:/app/config.json
    depends_on:
      - dopemux-litellm
    restart: unless-stopped
"""
        
        return {
            "litellm": litellm_snippet,
            "ccr": ccr_snippet,
        }

    @classmethod
    def get_instance(cls) -> "LaunchdServiceManager":
        """Get a singleton instance of the service manager."""
        if not hasattr(cls, "_instance"):
            cls._instance = cls()
        return cls._instance
