"""Frozen §5 clause table for TP-DMX-SECOND-BRAIN-ADR-CONTRACT-EVIDENCE-001.

Each entry: (clause_suffix, requirement_text, subject, rule_type, operator,
             machine_value, [source_fragments], [extra_covering_artifacts])

`requirement_text` is the packet §5 mandatory-coverage line, verbatim.
`source_fragments` MUST each be an exact substring of the ratified candidate
document (sha256 e4b28946...). Verified at generation time and re-verified by
the deterministic validator.
"""

CANDIDATE_SHA256 = "e4b28946156096319557fd25e0289c5de4b593b6239cc5c7af9b3efed259b66c"
RATIFICATION_BINDING_SHA256 = (
    "a23efdc676c499cc56b76c5fe321acd0bcf60871be18a33c7539e2350ba07b34"
)

CANDIDATE_PATH = (
    "docs/03-reference/architecture/second-brain/adr-candidates/"
    "second-brain-adr-candidates.md"
)

CONTRACT_DIR = "schemas/second_brain/contracts"

SPOOL = f"{CONTRACT_DIR}/local-spool-port.contract.json"
CUSTODY = f"{CONTRACT_DIR}/custody-port.contract.json"
OLC = f"{CONTRACT_DIR}/open-loop-candidate.schema.json"
TP = f"{CONTRACT_DIR}/task-proposal.schema.json"
TPR = f"{CONTRACT_DIR}/task-promotion-request.schema.json"
PIE = f"{CONTRACT_DIR}/project-identity-envelope.schema.json"
SCR = f"{CONTRACT_DIR}/service-capability-receipt.schema.json"

ADR_TITLES = {
    "ADR-SB-001": "Extension Boundary and Non-Authority",
    "ADR-SB-002": "Capture, Candidate, Review, and Promotion",
    "ADR-SB-003": "Recall Fusion and Provenance",
    "ADR-SB-004": "Domain, Classification, and Provider Policy",
    "ADR-SB-005": "Markdown Projection Contract",
    "ADR-SB-006": "Local Spool and Custody Interface",
    "ADR-SB-007": "Forget, Purge, and Residual Verification",
    "ADR-SB-008": "Open Loop and Task Proposal Boundary",
    "ADR-SB-009": "Single-Project Safety and Identity Dependencies",
    "ADR-SB-010": "UX Contract",
}

# Closed set of canonical authority targets. Second Brain is never a member;
# Dope-Context is advisory retrieval and is likewise never an authority target.
AUTHORITY_TARGETS = [
    "ConPort",
    "Dope-Memory",
    "Leantime",
    "Task Orchestrator",
    "dopeTask",
]

FORBIDDEN_AUTHORITY_CLAIMS = [
    "SECOND_BRAIN_AS_CANONICAL_DATABASE",
    "SECOND_BRAIN_AS_FOURTH_AUTHORITY_PLANE",
    "SECOND_BRAIN_PM_AUTHORITY",
    "SECOND_BRAIN_WORKFLOW_AUTHORITY",
    "DERIVED_READ_MODEL_AS_AUTHORITY",
]

IMPLEMENTATION_DEFERRED = [
    "DENIAL_FIXTURES",
    "RUNTIME_CONFORMANCE",
    "RETRIEVAL_BENCHMARKS",
    "PURGE_COMPLETENESS",
    "MULTI_PROJECT_ISOLATION",
    "SPLIT_BRAIN_PROOF",
    "ENCRYPTION_IMPLEMENTATION",
]

D_EXT = "Create a Dopemux PCP/DCP-compatible extension."
D_OWNS = (
    "It owns control logic, derived read models, projections, local spool "
    "coordination, purge coordination, and receipts only."
)
D_CANON_WRITES = "Canonical writes go to existing authorities."

CLAUSES = {
    "ADR-SB-001": [
        (
            "C01",
            "Second Brain is an extension/control plane",
            "second_brain.role",
            "CONSTANT",
            "EQUALS",
            "EXTENSION_CONTROL_PLANE",
            [D_EXT, D_OWNS],
            [],
        ),
        (
            "C02",
            "no canonical Second Brain database",
            "second_brain.canonical_database",
            "FORBID",
            "MUST_NOT_EXIST",
            "SECOND_BRAIN_CANONICAL_DATABASE",
            ["No canonical SB database", "Dedicated Second Brain database"],
            [],
        ),
        (
            "C03",
            "canonical writes target existing authorities",
            "second_brain.canonical_write.target",
            "AUTHORITY_TARGET",
            "IN",
            AUTHORITY_TARGETS,
            [D_CANON_WRITES],
            [],
        ),
        (
            "C04",
            "derived read models are non-canonical",
            "second_brain.derived_read_model.canonicality",
            "FORBID",
            "NOT_EQUALS",
            "CANONICAL",
            [D_OWNS, "No canonical SB database"],
            [],
        ),
        (
            "C05",
            "projection/spool/purge coordination does not confer authority",
            "second_brain.coordination.confers_authority",
            "FORBID",
            "EQUALS",
            False,
            [D_OWNS, D_CANON_WRITES],
            [],
        ),
        (
            "C06",
            "extension can be disabled without canonical-store migration",
            "second_brain.disable.requires_canonical_store_migration",
            "REQUIRE",
            "EQUALS",
            False,
            ["Disable extension without changing canonical stores"],
            [],
        ),
    ],
    "ADR-SB-002": [
        (
            "C01",
            "captured events → Dope-Memory",
            "second_brain.capture.captured_event.append_target",
            "AUTHORITY_TARGET",
            "EQUALS",
            "Dope-Memory",
            ["Append captured events and candidates to Dope-Memory"],
            [],
        ),
        (
            "C02",
            "candidates → Dope-Memory",
            "second_brain.capture.candidate.append_target",
            "AUTHORITY_TARGET",
            "EQUALS",
            "Dope-Memory",
            ["Append captured events and candidates to Dope-Memory"],
            [],
        ),
        (
            "C03",
            "review read model = non-canonical",
            "second_brain.review.read_model.canonicality",
            "FORBID",
            "NOT_EQUALS",
            "CANONICAL",
            ["build a non-canonical review read model"],
            [],
        ),
        (
            "C04",
            "affirmative review is digest-bound",
            "second_brain.review.affirmative.digest_binding",
            "REQUIRE",
            "MUST_EXIST",
            "REVIEW_DIGEST_SHA256",
            ["require digest-bound affirmative review"],
            [],
        ),
        (
            "C05",
            "default = DEFER / NO MUTATION",
            "second_brain.review.default_disposition",
            "FAIL_CLOSED",
            "DEFAULTS_TO",
            "DEFER_NO_MUTATION",
            ["Default DEFER/NO MUTATION"],
            [],
        ),
        (
            "C06",
            "approved action has exact canonical target",
            "second_brain.promotion.approved_action.canonical_target",
            "AUTHORITY_TARGET",
            "IN",
            AUTHORITY_TARGETS,
            ["route approved actions to exact canonical targets"],
            [],
        ),
        (
            "C07",
            "promotion receipt → Dope-Memory",
            "second_brain.promotion.receipt.append_target",
            "AUTHORITY_TARGET",
            "EQUALS",
            "Dope-Memory",
            ["append promotion receipts to Dope-Memory"],
            [],
        ),
        (
            "C08",
            "no cross-authority transaction fiction",
            "second_brain.promotion.cross_authority_transaction",
            "FORBID",
            "MUST_NOT_EXIST",
            "CROSS_AUTHORITY_ATOMIC_TRANSACTION",
            ["No cross-authority transaction fiction"],
            [],
        ),
    ],
    "ADR-SB-003": [
        (
            "C01",
            "authority-first fusion",
            "second_brain.recall.fusion.order",
            "ORDERING",
            "PRECEDES",
            ["AUTHORITY", "CHRONOLOGY", "SOURCE_NATIVE", "ADVISORY_RETRIEVAL"],
            ["Use deterministic authority-first fusion"],
            [],
        ),
        (
            "C02",
            "policy filtering occurs before model context",
            "second_brain.recall.policy_filter.stage",
            "ORDERING",
            "PRECEDES",
            ["POLICY_FILTER", "MODEL_CONTEXT_ASSEMBLY"],
            ["with pre-model policy filtering"],
            [],
        ),
        (
            "C03",
            "freshness represented",
            "second_brain.recall.response.freshness",
            "REQUIRE",
            "MUST_EXIST",
            "FRESHNESS_METADATA",
            ["freshness and contradiction detection"],
            [],
        ),
        (
            "C04",
            "contradictions represented",
            "second_brain.recall.response.contradictions",
            "REQUIRE",
            "MUST_EXIST",
            "CONTRADICTION_SET",
            ["freshness and contradiction detection"],
            [],
        ),
        (
            "C05",
            "advisory retrieval bounded and non-canonical",
            "second_brain.recall.advisory_retrieval.canonicality",
            "FORBID",
            "NOT_EQUALS",
            "CANONICAL",
            ["bounded advisory retrieval"],
            [],
        ),
        (
            "C06",
            "every response exposes evidence/access/uncertainty metadata",
            "second_brain.recall.response.required_metadata",
            "REQUIRE",
            "SUPERSET_OF",
            ["evidence", "access", "uncertainty"],
            ["evidence/access/uncertainty metadata on every response"],
            [],
        ),
        (
            "C07",
            "partial outage is explicit",
            "second_brain.recall.partial_outage.disclosure",
            "FAIL_CLOSED",
            "EQUALS",
            "EXPLICIT",
            ["Partial outages are explicit"],
            [],
        ),
        (
            "C08",
            "search rank cannot become truth",
            "second_brain.recall.search_rank.authority",
            "FORBID",
            "EQUALS",
            False,
            ["without allowing search rank to become truth"],
            [],
        ),
    ],
    "ADR-SB-004": [
        (
            "C01",
            "domain enum = project/hue/dom/shared",
            "second_brain.policy.domain",
            "ENUM",
            "SET_EQUALS",
            ["project", "hue", "dom", "shared"],
            ["Use project/hue/dom/shared"],
            [],
        ),
        (
            "C02",
            "classification enum = public/internal/confidential/restricted",
            "second_brain.policy.classification",
            "ENUM",
            "SET_EQUALS",
            ["public", "internal", "confidential", "restricted"],
            ["and public/internal/confidential/restricted"],
            [],
        ),
        (
            "C03",
            "identity/grant/provider/embedding/custody/backup/operation "
            "eligibility evaluated pre-disclosure",
            "second_brain.policy.evaluation.stage",
            "ORDERING",
            "PRECEDES",
            [
                "POLICY_EVALUATION",
                "RETRIEVAL_DISCLOSURE",
                "MODEL_CONTEXT_ASSEMBLY",
            ],
            [
                "Evaluate identity, grants, provider, embedding, custody, "
                "backup, and operation policy before retrieval disclosure or "
                "model context assembly."
            ],
            [],
        ),
        (
            "C04",
            "UNKNOWN eligibility denies",
            "second_brain.policy.eligibility.unknown",
            "FAIL_CLOSED",
            "EQUALS",
            "DENY",
            ["Unknown denies."],
            [],
        ),
        (
            "C05",
            "Dom real-data path disabled / synthetic-only",
            "second_brain.policy.domain.dom.data_path",
            "CAPABILITY_GATE",
            "EQUALS",
            "SYNTHETIC_ONLY",
            ["Dom synthetic-only"],
            [],
        ),
        (
            "C06",
            "shared requires grant",
            "second_brain.policy.domain.shared.requires_grant",
            "REQUIRE",
            "EQUALS",
            True,
            ["Shared disabled without grant"],
            [],
        ),
        (
            "C07",
            "confidential/restricted semantic indexing disabled in v1",
            "second_brain.policy.semantic_indexing.enabled_classifications",
            "CAPABILITY_GATE",
            "SET_EQUALS",
            ["public", "internal"],
            ["No confidential/restricted semantic indexing in v1"],
            [],
        ),
    ],
    "ADR-SB-005": [
        (
            "C01",
            "projection derives from canonical snapshot revision",
            "second_brain.projection.source",
            "REQUIRE",
            "EQUALS",
            "CANONICAL_SNAPSHOT_REVISION",
            ["Compile deterministic Markdown from canonical snapshot revisions"],
            [],
        ),
        (
            "C02",
            "stable paths",
            "second_brain.projection.path_stability",
            "REQUIRE",
            "EQUALS",
            "STABLE",
            ["with stable paths"],
            [],
        ),
        (
            "C03",
            "managed/manual regions",
            "second_brain.projection.region_kinds",
            "ENUM",
            "SET_EQUALS",
            ["managed", "manual"],
            ["managed/manual regions"],
            [],
        ),
        (
            "C04",
            "visible freshness",
            "second_brain.projection.freshness_visibility",
            "REQUIRE",
            "EQUALS",
            "VISIBLE",
            ["visible freshness"],
            [],
        ),
        (
            "C05",
            "content hash",
            "second_brain.projection.content_hash",
            "REQUIRE",
            "MUST_EXIST",
            "PROJECTION_CONTENT_SHA256",
            ["content hashes"],
            [],
        ),
        (
            "C06",
            "purge propagation",
            "second_brain.projection.purge_propagation",
            "REQUIRE",
            "EQUALS",
            True,
            ["purge propagation"],
            [],
        ),
        (
            "C07",
            "no silent write-back",
            "second_brain.projection.write_back",
            "FORBID",
            "MUST_NOT_EXIST",
            "SILENT_WRITE_BACK",
            ["and no silent write-back"],
            [],
        ),
        (
            "C08",
            "canonical source wins",
            "second_brain.projection.conflict_resolution",
            "REQUIRE",
            "EQUALS",
            "CANONICAL_SOURCE_WINS",
            ["Canonical sources always win"],
            [],
        ),
        (
            "C09",
            "Obsidian optional, never authority",
            "second_brain.projection.obsidian.role",
            "FORBID",
            "EQUALS",
            "OPTIONAL_OPENER_NEVER_AUTHORITY",
            [
                "Obsidian is an optional opener.",
                "Markdown and Obsidian must not become accidental authorities",
            ],
            [],
        ),
    ],
    "ADR-SB-006": [
        (
            "C01",
            "LocalSpoolPort exists as a machine interface contract",
            "second_brain.local_spool_port",
            "INTERFACE_REQUIREMENT",
            "MUST_EXIST",
            "LocalSpoolPort",
            ["Define `LocalSpoolPort` and `CustodyPort`."],
            [SPOOL],
        ),
        (
            "C02",
            "CustodyPort exists as a machine interface contract",
            "second_brain.custody_port",
            "INTERFACE_REQUIREMENT",
            "MUST_EXIST",
            "CustodyPort",
            ["Define `LocalSpoolPort` and `CustodyPort`."],
            [CUSTODY],
        ),
        (
            "C03",
            "spool record is non-canonical",
            "second_brain.local_spool.record.canonicality",
            "FORBID",
            "NOT_EQUALS",
            "CANONICAL",
            ["Spool records are non-canonical"],
            [SPOOL],
        ),
        (
            "C04",
            "identity/domain/class scoped",
            "second_brain.local_spool.record.scope_keys",
            "REQUIRE",
            "SUPERSET_OF",
            ["identity", "domain", "classification"],
            ["identity/domain/class scoped"],
            [SPOOL],
        ),
        (
            "C05",
            "deterministic",
            "second_brain.local_spool.record.determinism",
            "REQUIRE",
            "EQUALS",
            "DETERMINISTIC",
            ["deterministic"],
            [SPOOL],
        ),
        (
            "C06",
            "integrity protected",
            "second_brain.local_spool.record.integrity",
            "REQUIRE",
            "MUST_EXIST",
            "INTEGRITY_DIGEST",
            ["integrity-protected"],
            [SPOOL],
        ),
        (
            "C07",
            "short-lived",
            "second_brain.local_spool.record.retention",
            "LIFECYCLE",
            "EQUALS",
            "SHORT_LIVED_BOUNDED_TTL",
            ["short-lived"],
            [SPOOL],
        ),
        (
            "C08",
            "idempotently flushable",
            "second_brain.local_spool.flush.idempotency",
            "REQUIRE",
            "EQUALS",
            True,
            ["idempotently flushed"],
            [SPOOL],
        ),
        (
            "C09",
            "purge aware",
            "second_brain.local_spool.purge_participation",
            "REQUIRE",
            "EQUALS",
            True,
            ["purge-aware"],
            [SPOOL],
        ),
        (
            "C10",
            "never remotely backed up",
            "second_brain.local_spool.remote_backup",
            "FORBID",
            "EQUALS",
            False,
            ["never remote backed up"],
            [SPOOL, CUSTODY],
        ),
        (
            "C11",
            "public allowed",
            "second_brain.local_spool.classification.public",
            "CAPABILITY_GATE",
            "EQUALS",
            "ALLOWED",
            ["Public is allowed"],
            [SPOOL],
        ),
        (
            "C12",
            "internal requires OS-protected storage",
            "second_brain.local_spool.classification.internal",
            "CAPABILITY_GATE",
            "EQUALS",
            "ALLOWED_REQUIRES_OS_PROTECTED_STORAGE",
            ["internal requires OS-protected storage"],
            [SPOOL],
        ),
        (
            "C13",
            "confidential/restricted disabled until verified "
            "encryption/key ownership",
            "second_brain.local_spool.classification.confidential_restricted",
            "CAPABILITY_GATE",
            "EQUALS",
            "DISABLED_UNTIL_VERIFIED_ENCRYPTION_AND_KEY_OWNERSHIP",
            [
                "confidential/restricted remain disabled until verified "
                "encryption and key ownership"
            ],
            [SPOOL, CUSTODY],
        ),
        (
            "C14",
            "unknown class denied",
            "second_brain.local_spool.classification.unknown",
            "FAIL_CLOSED",
            "EQUALS",
            "DENY",
            ["No unknown-class spooling"],
            [SPOOL],
        ),
    ],
    "ADR-SB-007": [
        (
            "C01",
            "Archive != Forget != Purge",
            "second_brain.deletion.operations",
            "ENUM",
            "SET_EQUALS",
            ["ARCHIVE", "FORGET", "PURGE"],
            [
                "Model Archive, Forget, and Purge separately.",
                "Hide-from-view, retrieval denial, logical tombstone, physical "
                "deletion, and backup expiry are different operations.",
            ],
            [],
        ),
        (
            "C02",
            "dependency graph",
            "second_brain.purge.dependency_graph",
            "REQUIRE",
            "MUST_EXIST",
            "PURGE_DEPENDENCY_GRAPH",
            ["Build a dependency graph"],
            [],
        ),
        (
            "C03",
            "impact preview",
            "second_brain.purge.impact_preview",
            "REQUIRE",
            "MUST_EXIST",
            "PURGE_IMPACT_PREVIEW",
            ["impact preview"],
            [],
        ),
        (
            "C04",
            "explicit approval",
            "second_brain.purge.approval",
            "REQUIRE",
            "EQUALS",
            "EXPLICIT_OPERATOR_APPROVAL",
            ["explicit approval"],
            [],
        ),
        (
            "C05",
            "per-surface receipts",
            "second_brain.purge.receipts.granularity",
            "REQUIRE",
            "EQUALS",
            "PER_SURFACE",
            ["per-surface receipts"],
            [],
        ),
        (
            "C06",
            "residual scan",
            "second_brain.purge.residual_scan",
            "REQUIRE",
            "MUST_EXIST",
            "RESIDUAL_SCAN",
            ["residual scan"],
            [],
        ),
        (
            "C07",
            "searchable residual count must equal zero before success",
            "second_brain.purge.searchable_residual_count",
            "FAIL_CLOSED",
            "EQUALS",
            0,
            ["Searchable residual count must be zero before success."],
            [],
        ),
        (
            "C08",
            "impossible physical deletion → tombstone/retrieval denial",
            "second_brain.purge.physical_deletion_impossible.disposition",
            "STATE_TRANSITION",
            "EQUALS",
            "EXPLICIT_TOMBSTONE_AND_RETRIEVAL_DENIAL",
            [
                "Impossible physical deletion uses explicit "
                "tombstone/retrieval denial"
            ],
            [],
        ),
        (
            "C09",
            "backup expiry may remain pending",
            "second_brain.purge.backup_expiry.state",
            "LIFECYCLE",
            "EQUALS",
            "PENDING_BACKUP_EXPIRY",
            ["and pending backup-expiry state"],
            [],
        ),
        (
            "C10",
            "irreversible steps require immediate confirmation",
            "second_brain.purge.irreversible_step.confirmation",
            "REQUIRE",
            "EQUALS",
            "IMMEDIATE",
            ["Irreversible steps require immediate confirmation"],
            [],
        ),
        (
            "C11",
            "derived representations participate",
            "second_brain.purge.derived_representations.participate",
            "REQUIRE",
            "EQUALS",
            True,
            ["Derived representations participate"],
            [],
        ),
    ],
    "ADR-SB-008": [
        (
            "C01",
            "OpenLoopCandidate exists as a machine data contract",
            "second_brain.open_loop_candidate",
            "INTERFACE_REQUIREMENT",
            "MUST_EXIST",
            "OpenLoopCandidate",
            ["Represent detected loops as suggested candidates."],
            [OLC],
        ),
        (
            "C02",
            "TaskProposal exists as a separate machine data contract",
            "second_brain.task_proposal",
            "INTERFACE_REQUIREMENT",
            "MUST_EXIST",
            "TaskProposal",
            [
                "Any task-shaped behavior must be represented as a separate "
                "`TaskProposal`"
            ],
            [TP],
        ),
        (
            "C03",
            "TaskPromotionRequest exists as a separate machine contract",
            "second_brain.task_promotion_request",
            "INTERFACE_REQUIREMENT",
            "MUST_EXIST",
            "TaskPromotionRequest",
            ["mutated only through the disabled `TaskPromotionRequest` path"],
            [TPR],
        ),
        (
            "C04",
            "confirmed open-loop events → Dope-Memory",
            "second_brain.open_loop.confirmed_event.append_target",
            "AUTHORITY_TARGET",
            "EQUALS",
            "Dope-Memory",
            ["Confirmation appends open/close/cancel events to Dope-Memory"],
            [],
        ),
        (
            "C05",
            "active loop list = derived",
            "second_brain.open_loop.active_list.canonicality",
            "FORBID",
            "NOT_EQUALS",
            "CANONICAL",
            ["the active list is derived"],
            [],
        ),
        (
            "C06",
            "task mutation requires Leantime + Task Orchestrator proof + "
            "explicit approval",
            "second_brain.task_mutation.preconditions",
            "CAPABILITY_GATE",
            "SET_EQUALS",
            [
                "LEANTIME_PROOF",
                "TASK_ORCHESTRATOR_PROOF",
                "EXPLICIT_OPERATOR_APPROVAL",
            ],
            [
                "Actual task creation requires Leantime plus Task Orchestrator "
                "proof and explicit approval"
            ],
            [TPR],
        ),
        (
            "C07",
            "task promotion initially disabled",
            "second_brain.task_promotion.enabled",
            "CAPABILITY_GATE",
            "EQUALS",
            False,
            ["it is disabled initially"],
            [TPR],
        ),
        (
            "C08",
            "open loop has no assignee",
            "second_brain.open_loop.field.assignee",
            "FORBID",
            "MUST_NOT_EXIST",
            "assignee",
            ["may never carry an assignee"],
            [OLC],
        ),
        (
            "C09",
            "no PM priority",
            "second_brain.open_loop.field.pm_priority",
            "FORBID",
            "MUST_NOT_EXIST",
            "pm_priority",
            ["PM priority"],
            [OLC],
        ),
        (
            "C10",
            "no workflow status",
            "second_brain.open_loop.field.workflow_status",
            "FORBID",
            "MUST_NOT_EXIST",
            "workflow_status",
            ["workflow status"],
            [OLC],
        ),
        (
            "C11",
            "no sprint state",
            "second_brain.open_loop.field.sprint_state",
            "FORBID",
            "MUST_NOT_EXIST",
            "sprint_state",
            ["sprint state"],
            [OLC],
        ),
        (
            "C12",
            "no ownership assignment",
            "second_brain.open_loop.field.ownership",
            "FORBID",
            "MUST_NOT_EXIST",
            "ownership",
            ["ownership assignment"],
            [OLC],
        ),
        (
            "C13",
            "no due-driven escalation",
            "second_brain.open_loop.due_driven_escalation",
            "FORBID",
            "EQUALS",
            False,
            [
                "due-driven escalation",
                "`due_at` cannot trigger scheduling or escalation",
            ],
            [OLC],
        ),
        (
            "C14",
            "no automatic scheduling",
            "second_brain.open_loop.automatic_scheduling",
            "FORBID",
            "EQUALS",
            False,
            ["automatic scheduling"],
            [OLC],
        ),
        (
            "C15",
            "no task completion state",
            "second_brain.open_loop.field.task_completion_state",
            "FORBID",
            "MUST_NOT_EXIST",
            "task_completion_state",
            ["or task completion state"],
            [OLC],
        ),
        (
            "C16",
            "due_at is display/advisory only",
            "second_brain.open_loop.due_at.semantics",
            "CONSTANT",
            "EQUALS",
            "ADVISORY_DISPLAY_METADATA_ONLY",
            ["`OpenLoopCandidate.due_at` is advisory display metadata only."],
            [OLC],
        ),
    ],
    "ADR-SB-009": [
        (
            "C01",
            "registry-backed project identity envelope",
            "second_brain.project_identity_envelope",
            "INTERFACE_REQUIREMENT",
            "MUST_EXIST",
            "ProjectIdentityEnvelope",
            ["Require registry-backed identity envelopes"],
            [PIE],
        ),
        (
            "C02",
            "current service capability receipt",
            "second_brain.service_capability_receipt",
            "INTERFACE_REQUIREMENT",
            "MUST_EXIST",
            "ServiceCapabilityReceipt",
            [
                "current service capability receipts for authority operations",
            ],
            [SCR],
        ),
        (
            "C03",
            "one active automatic-capture project",
            "second_brain.automatic_capture.active_project_count",
            "MAXIMUM",
            "LESS_THAN_OR_EQUAL",
            1,
            ["Permit one active automatic-capture project"],
            [PIE],
        ),
        (
            "C04",
            "explicit project switching",
            "second_brain.project_switch.mode",
            "REQUIRE",
            "EQUALS",
            "EXPLICIT",
            ["explicit project switching"],
            [PIE],
        ),
        (
            "C05",
            "writer epoch",
            "second_brain.writer_epoch",
            "REQUIRE",
            "MUST_EXIST",
            "WRITER_EPOCH",
            ["writer epochs"],
            [PIE],
        ),
        (
            "C06",
            "wrong-project denial",
            "second_brain.write.wrong_project",
            "FAIL_CLOSED",
            "EQUALS",
            "DENY",
            ["and wrong-project denial"],
            [PIE, SCR],
        ),
        (
            "C07",
            "port/path/current-directory cannot establish write authority",
            "second_brain.write_authority.rejected_identity_sources",
            "FORBID",
            "SUPERSET_OF",
            ["PORT", "PATH_HASH", "CURRENT_DIRECTORY", "SINGLETON_EVENT_STREAM"],
            [
                "Path hashes, ports, and singleton event streams cannot safely "
                "establish canonical project identity.",
                "Implicit current-directory project selection for writes",
            ],
            [PIE],
        ),
        (
            "C08",
            "multi-project background capture disabled until isolation proof",
            "second_brain.multi_project_background_capture.enabled",
            "CAPABILITY_GATE",
            "EQUALS",
            False,
            [
                "Multi-project background capture remains disabled until "
                "isolation proof."
            ],
            [PIE],
        ),
    ],
    "ADR-SB-010": [
        (
            "C01",
            "operations = Capture / Recall / Review",
            "second_brain.ux.operations",
            "ENUM",
            "SET_EQUALS",
            ["Capture", "Recall", "Review"],
            ["Use Capture, Recall, Review"],
            [],
        ),
        (
            "C02",
            "one dominant next action",
            "second_brain.ux.dominant_next_action_count",
            "MAXIMUM",
            "LESS_THAN_OR_EQUAL",
            1,
            ["one dominant next action"],
            [],
        ),
        (
            "C03",
            "visible queue maximum = 7",
            "second_brain.ux.visible_queue_max",
            "MAXIMUM",
            "LESS_THAN_OR_EQUAL",
            7,
            ["at most seven visible queue items"],
            [],
        ),
        (
            "C04",
            "answer-first recall",
            "second_brain.ux.recall.presentation",
            "ORDERING",
            "PRECEDES",
            ["ANSWER", "EVIDENCE"],
            ["answer-first recall"],
            [],
        ),
        (
            "C05",
            "evidence one action away",
            "second_brain.ux.evidence.max_actions_away",
            "MAXIMUM",
            "LESS_THAN_OR_EQUAL",
            1,
            ["evidence one action away"],
            [],
        ),
        (
            "C06",
            "session-end batching",
            "second_brain.ux.notification.batching",
            "REQUIRE",
            "EQUALS",
            "SESSION_END",
            ["session-end batching"],
            [],
        ),
        (
            "C07",
            "immediate interruption only for: privacy, identity, data-loss, "
            "irreversible-action, authority-conflict",
            "second_brain.ux.immediate_interruption.allowed_conditions",
            "ENUM",
            "SET_EQUALS",
            [
                "privacy",
                "identity",
                "data-loss",
                "irreversible-action",
                "authority-conflict",
            ],
            [
                "immediate interruption only for privacy, identity, data-loss, "
                "irreversible-action, or authority-conflict conditions"
            ],
            [],
        ),
        (
            "C08",
            "consequential default = DEFER or CANCEL",
            "second_brain.ux.consequential_default",
            "FAIL_CLOSED",
            "IN",
            ["DEFER", "CANCEL"],
            ["Consequential defaults are DEFER or CANCEL."],
            [],
        ),
        (
            "C09",
            "no productivity scoring",
            "second_brain.ux.productivity_scoring",
            "FORBID",
            "EQUALS",
            False,
            ["No productivity scoring or surprise writes"],
            [],
        ),
        (
            "C10",
            "no surprise writes",
            "second_brain.ux.surprise_writes",
            "FORBID",
            "EQUALS",
            False,
            ["No productivity scoring or surprise writes"],
            [],
        ),
    ],
}
