# GitHub Sponsors configuration
github: [hu3mann]
# patreon: yourPatreonName
# ko_fi: yourKofiName
# buy_me_a_coffee: yourBmacName
# open_collective: yourCollectiveName
# polar: yourPolarName
# thanks_dev: yourThanksDevName
custom: ['https://github.com/sponsors/hu3mann']