#!/usr/bin/env python3
"""Deterministic assembler for the TP-DMX-FDOS-004 ChatGPT Project 40-source upload set.

Reads the resolved 37-slot source spec (source_set_v4.json) and the pre-captured
open-PR evidence (proof/.../open-pr-*.json, OPEN_PRS_INITIAL.json) plus their
classifications (pr_classifications.json), copies current-main source bytes
byte-for-byte via `git show <EXECUTION_BASE_SHA>:<path>`, and emits the
UPLOAD_FILES/ directory, source manifest, open-PR impact ledger, freshness
policy, and supporting reports under out/chatgpt-project-upload-set/.

No network calls. All open-PR data is consumed from previously captured
evidence files -- this script never invokes `gh`.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

PACKET_ID = "TP-DMX-FDOS-004-CHATGPT-PROJECT-SOURCE-REFRESH"
REPO = "DDD-Enterprises/dopemux-mvp"

FRESHNESS_POLICY_TEXT = """# 38_SOURCE_FRESHNESS_POLICY

> GENERATED ARTIFACT -- non-authoritative. This file describes how to interpret
> the freshness of every other file in this upload set. It is generated by
> `scripts/project_sources/build_chatgpt_project_sources.py` for packet
> `{packet_id}` and is bound to `execution_base_sha: {execution_base_sha}`.
> It does not itself establish runtime, governance, or architectural truth.

## 1. Freshness Classes

- `LIVE_RESOLVE` -- must always be re-resolved live against the running system
  or the current open-PR inventory; never trust a snapshot for these claims.
- `VOLATILE_14_DAYS` -- treat as stale after 14 days from `generated_at` below,
  or immediately if `origin/main` has moved past `execution_base_sha` for the
  file's own path.
- `SYSTEM_SNAPSHOT_30_DAYS` -- system/architecture reference docs; treat as
  stale after 30 days or on any merged PR touching the described service.
- `STABLE_CONTRACT_90_DAYS` -- schemas and contracts that change rarely; treat
  as stale after 90 days or immediately on any schema-file diff.
- `GENERATED_FOR_BASE_SHA` -- applies to slots 38-40 themselves; valid only
  for the exact `execution_base_sha` and open-PR snapshot recorded in this
  package; regenerate on any drift in either.
- `HISTORICAL_ONLY` -- not used by any slot in this package; reserved for
  future archival-only sources.

## 2. Required Rules

1. Runtime state and open-PR status are always resolved live -- this package
   is a point-in-time snapshot, not a live feed.
2. This package is bound to exactly one `execution_base_sha`
   (`{execution_base_sha}`). A copy of this package without a recorded base
   SHA is advisory only and must not be treated as current-main authority.
3. Any source whose tracked git blob SHA (recorded in
   `39_PROJECT_SOURCE_MANIFEST.json`) differs from the blob at the then-current
   `origin/main` for the same path is stale.
4. Any merged PR touching a watched path family (see
   `40_OPEN_PR_IMPACT_LEDGER.md` section 2) triggers source-set reevaluation
   for this package.
5. Any merged PR affecting a selected source (see the per-PR
   `source_slots_affected` field in the ledger) triggers regeneration of
   those exact slots at minimum, and a full package rebuild is recommended.
6. Any change to the embedded-audit schema (slot 31) or PR Steward
   merge-readiness schema (slot 33) triggers full package regeneration.
7. Any change to the Task Packet canonical schema (slot 25) triggers full
   package regeneration.
8. Any change to the runtime authority manifest (slot 10) triggers full
   package regeneration.
9. A source may remain useful for orientation while stale, but a stale source
   must not be cited to authorize a current implementation or merge
   decision -- re-resolve it live first.
10. Strict isolated-input acceptance work must not be performed inside a
    ChatGPT Project whose inherited files violate the acceptance input gate
    for that work (e.g. a Project still containing files this refresh
    explicitly excluded).
11. Previous package-verification verdicts (e.g. any prior
    `Package Verification Process.txt`-style artifact) are case-specific
    historical records, not a reusable verification process for this or any
    other package.

## 3. Disposition Note

This package's disposition and material-open-PR count are recorded in
`39_PROJECT_SOURCE_MANIFEST.json` (`package_disposition`,
`material_open_pr_count`) and in `40_OPEN_PR_IMPACT_LEDGER.md`. A disposition
of `CURRENT_MAIN_VALID_PENDING_OPEN_PR_REFRESH` means the package is valid for
`{execution_base_sha}` today but must be regenerated if any material PR merges.
No disposition in this family is ever "final forever."
"""


def sh(args: list[str], cwd: Path) -> str:
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True, check=True)
    return result.stdout


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_blob_sha(repo_root: Path, execution_base_sha: str, path: str) -> str:
    return sh(["git", "rev-parse", f"{execution_base_sha}:{path}"], repo_root).strip()


def git_show_bytes(repo_root: Path, execution_base_sha: str, path: str) -> bytes:
    result = subprocess.run(
        ["git", "show", f"{execution_base_sha}:{path}"],
        cwd=repo_root,
        capture_output=True,
        check=True,
    )
    return result.stdout


def build_copied_slots(repo_root: Path, execution_base_sha: str, source_set: dict, upload_dir: Path) -> list[dict]:
    entries = []
    for slot in source_set["slots"]:
        path = slot["source_path"]
        blob_sha = git_blob_sha(repo_root, execution_base_sha, path)
        data = git_show_bytes(repo_root, execution_base_sha, path)
        out_path = upload_dir / slot["bundle_filename"]
        out_path.write_bytes(data)
        entries.append(
            {
                "slot": slot["slot"],
                "bundle_filename": slot["bundle_filename"],
                "artifact_type": "copied_source",
                "source_path": path,
                "source_commit_sha": execution_base_sha,
                "source_blob_sha": blob_sha,
                "sha256": sha256_bytes(data),
                "bytes": len(data),
                "authority_class": slot["authority_class"],
                "freshness_class": slot["freshness_class"],
                "generated": False,
                "current_main_only": True,
                "open_pr_content_included": False,
                "notes": [slot["rationale"]],
                "rejected_candidates": slot.get("rejected_candidates", []),
            }
        )
    return entries


def load_captured_prs(open_pr_dir: Path) -> list[dict]:
    prs = []
    for f in sorted(open_pr_dir.glob("open-pr-*.json")):
        prs.append(json.loads(f.read_text()))
    return prs


WATCHED_PATH_FAMILIES = [
    "AGENTS.md", "RULES.md", "PROJECT.md", "ARCHITECTURE.md", "PM_PLANE.md",
    "SERVICE_CATALOG.md", "TRUTH_*.md", "SYSTEM_*.md",
    "docs/03-reference/governance/**", "docs/03-reference/truth/**",
    "docs/03-reference/systems/**", "docs/03-reference/planes/**",
    "docs/ops/embedded-audit.md", "docs/ops/pr-steward.md", "schemas/proof/**",
    "schemas/pr_steward/**", "config/runtime_authority_manifest.json",
    "scripts/verify_runtime_authority.py", "config/ai/model-routing.policy.yaml",
    "docs/90-adr/**", "tools/pr_steward/**", "src/dopemux_pr_merge_specialist/**",
    "src/dopemux/dcp/**", "src/dopemux/mcp/**", "mcp_catalog.yaml", "schemas/mcp/**",
    "services/repo-truth-extractor/**", "services/dope-context/**",
    "services/task-orchestrator/**", "services/dopecon-bridge/**",
    "services/working-memory-assistant/**", "src/conport/**",
]


def build_pr_ledger_entries(prs: list[dict], classifications: dict, changed_file_counts: dict) -> list[dict]:
    entries = []
    for pr in prs:
        n = str(pr["number"])
        c = classifications["classifications"].get(n)
        if c is None:
            raise SystemExit(f"FATAL: open PR #{n} has no classification entry -- fail-closed")
        files = [f["path"] for f in pr.get("files", [])]
        entries.append(
            {
                "pr_number": pr["number"],
                "title": pr["title"],
                "url": pr["url"],
                "state": pr["state"],
                "is_draft": pr["isDraft"],
                "base_branch": pr["baseRefName"],
                "head_branch": pr["headRefName"],
                "head_sha": pr["headRefOid"],
                "merge_state_status": pr["mergeStateStatus"],
                "updated_at": pr["updatedAt"],
                "changed_file_count": changed_file_counts.get(n, len(files)),
                "watched_path_sample": files[:15],
                "classification": c["classification"],
                "evidence": c["evidence"],
                "current_main_effect": c["current_main_effect"],
                "action_if_merged": c["action_if_merged"],
                "source_slots_affected": c["source_slots_affected"],
                "contradiction_or_overlap_notes": c["contradiction_or_overlap_notes"],
                "confidence": c["confidence"],
            }
        )
    return entries


def render_ledger_md(entries: list[dict], execution_base_sha: str, generated_at: str) -> str:
    material = [e for e in entries if e["classification"] in ("SOURCE_SET_CHANGES_IF_MERGED", "SOURCE_CONTENT_REFRESH_IF_MERGED")]
    lines = []
    lines.append("# 40_OPEN_PR_IMPACT_LEDGER")
    lines.append("")
    lines.append("> This ledger is candidate-future-authority context only.")
    lines.append("> No unmerged PR content is represented as current-main truth.")
    lines.append("")
    lines.append("```yaml")
    lines.append(f"captured_at: {generated_at}")
    lines.append(f"execution_base_sha: {execution_base_sha}")
    lines.append(f"open_pr_count: {len(entries)}")
    lines.append(f"material_open_pr_count: {len(material)}")
    lines.append("regeneration_required_if_any_material_pr_merges: true")
    lines.append("```")
    lines.append("")
    lines.append("## 1. Repository")
    lines.append("")
    lines.append(f"`{REPO}`, default branch `main`.")
    lines.append("")
    lines.append("## 2. Watched Path Families")
    lines.append("")
    lines.append("A PR is presumptively material if it touches any of:")
    lines.append("")
    lines.append("```text")
    lines.extend(WATCHED_PATH_FAMILIES)
    lines.append("```")
    lines.append("")
    lines.append("Touching a watched path is a trigger for review, not automatic proof of impact.")
    lines.append("")
    lines.append("## 3. Per-PR Ledger")
    lines.append("")
    for e in entries:
        lines.append(f"### PR #{e['pr_number']} -- {e['title']}")
        lines.append("")
        lines.append(f"- URL: {e['url']}")
        lines.append(f"- State: {e['state']} (draft: {e['is_draft']})")
        lines.append(f"- Base branch: `{e['base_branch']}`")
        lines.append(f"- Head branch: `{e['head_branch']}`")
        lines.append(f"- Head SHA: `{e['head_sha']}`")
        lines.append(f"- Merge-state status: {e['merge_state_status']}")
        lines.append(f"- Updated: {e['updated_at']}")
        lines.append(f"- Changed-file count: {e['changed_file_count']}")
        lines.append(f"- **Classification: {e['classification']}**")
        lines.append(f"- Evidence: {e['evidence']}")
        lines.append(f"- Current-main effect: {e['current_main_effect']}")
        lines.append(f"- Action if merged: {e['action_if_merged']}")
        lines.append(f"- Source slots affected: {e['source_slots_affected'] or 'none'}")
        lines.append(f"- Contradiction/overlap notes: {e['contradiction_or_overlap_notes']}")
        lines.append(f"- Confidence: {e['confidence']}")
        if e["watched_path_sample"]:
            lines.append("- Sample changed paths:")
            for p in e["watched_path_sample"]:
                lines.append(f"    - `{p}`")
        lines.append("")
    lines.append("## 4. Conservation Check")
    lines.append("")
    lines.append(f"- Open PR inventory count: {len(entries)}")
    lines.append(f"- Ledger entry count: {len(entries)}")
    lines.append("- Every PR number appears exactly once above (enforced by the build script's fail-closed classification lookup).")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_source_resolution_report(copied_entries: list[dict]) -> str:
    lines = ["# SOURCE_RESOLUTION_REPORT", "", "For every slot: logical slot, selected source, rejected candidates, authority class, blob SHA, content SHA-256, byte count, rationale.", ""]
    for e in copied_entries:
        lines.append(f"## Slot {e['slot']:02d} -- {e['bundle_filename']}")
        lines.append("")
        lines.append(f"- Selected source path: `{e['source_path']}`")
        lines.append(f"- Authority class: {e['authority_class']}")
        lines.append(f"- Freshness class: {e['freshness_class']}")
        lines.append(f"- Source blob SHA: `{e['source_blob_sha']}`")
        lines.append(f"- Content SHA-256: `{e['sha256']}`")
        lines.append(f"- Bytes: {e['bytes']}")
        lines.append(f"- Rationale: {e['notes'][0]}")
        if e["rejected_candidates"]:
            lines.append("- Rejected candidates:")
            for r in e["rejected_candidates"]:
                lines.append(f"    - `{r['path']}` -- {r['reason']}: {r['evidence']}")
        else:
            lines.append("- Rejected candidates: none (single tracked candidate)")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_rejection_ledger(copied_entries: list[dict]) -> str:
    lines = ["# SOURCE_REJECTION_LEDGER", "", "Every rejected candidate for a selected slot, classified.", ""]
    any_rejections = False
    for e in copied_entries:
        for r in e["rejected_candidates"]:
            any_rejections = True
            lines.append(f"- `{r['path']}` (candidate for slot {e['slot']:02d} / {e['bundle_filename']}) -- **{r['reason']}**: {r['evidence']}")
    if not any_rejections:
        lines.append("(no rejected candidates recorded)")
    lines.append("")
    lines.append("## Explicitly Adjudicated Exclusions (packet section 18)")
    lines.append("")
    adjudications = [
        ("Package Verification Process.txt", "HISTORICAL_CASE_ARTIFACT", "Case-specific historical acceptance verdict for a prior package; not present in the current tracked tree and explicitly excluded by packet invariant 8."),
        ("Multi-Model Routing Policy.txt", "WRONG_IDENTITY", "Prior oversized/wrong-identity multi-model routing artifact; not present in the current tracked tree and explicitly excluded by packet invariant 9. The correctly-scoped current source is slot 34 (config/ai/model-routing.policy.yaml)."),
        ("REPO_STRUCTURE.md", "GENERATED_NAVIGATION_NOISE", "Not present in current tracked tree; historical navigation dump from a prior upload pass."),
        ("TOP40_SELECTION_RATIONALE.md", "HISTORICAL_CASE_ARTIFACT", "Not present in current tracked tree; rationale doc for a prior (FDOS-003) selection, superseded by this packet's own SOURCE_RESOLUTION_REPORT.md."),
        ("DRIFT_AND_GAPS_SUMMARY.md", "HISTORICAL_CASE_ARTIFACT", "Not present in current tracked tree as a top-level file; superseded by 40_OPEN_PR_IMPACT_LEDGER.md and this packet's own reports."),
        ("CHATGPT_PROJECT_UPLOAD_SET.md", "GENERATED_NAVIGATION_NOISE", "Prior generated navigation/meta doc referenced by doc-trust-map.md as advisory-only navigation index, not source authority."),
        ("INDEX.md", "GENERATED_NAVIGATION_NOISE", "task-packets/INDEX.md is a generated navigation index, explicitly excluded by packet section 9."),
        ("agents.instructions.md", "TOOL_SPECIFIC_OUT_OF_SCOPE", "config/instructions/agents.instructions.md is broad Copilot custom-agent authoring instruction, explicitly excluded by packet section 9; distinct from and not a substitute for AGENTS.md (slot 01)."),
        ("PAL_CHAINING_DOCTRINE.md", "REDUNDANT_WITH_HIGHER_AUTHORITY", "Remains a valid repo reference per packet section 18, but the compressed operational rules (slot 24) plus live AGENTS.md (slot 01) adequately preserve the execution contract for this upload set; not present at a root path in the current tracked tree in any case."),
        ("PAL_PACKET_TEMPLATE.md", "GENERATED_NAVIGATION_NOISE", "No such file exists in the current tracked tree; only task-packets/TEMPLATE_TASK_PACKET.md (selected, slot 26) is present."),
        ("TEMPLATE_TASK_PACKET.md (installer scaffolding copies)", "TOOL_SPECIFIC_OUT_OF_SCOPE", "src/dopemux/templates/init/**/TEMPLATE_TASK_PACKET.md are installer scaffolding copies for newly-initialized repos, not this repo's own authoring template (slot 26 uses task-packets/TEMPLATE_TASK_PACKET.md directly)."),
    ]
    for name, cls, reason in adjudications:
        lines.append(f"- `{name}` -- **{cls}**: {reason}")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_current_main_40(copied_entries: list[dict], execution_base_sha: str) -> str:
    lines = [f"# CURRENT_MAIN_40", "", f"execution_base_sha: `{execution_base_sha}`", "", "| Slot | Bundle filename | Source path | Bytes | SHA-256 |", "| --- | --- | --- | --- | --- |"]
    for e in copied_entries:
        lines.append(f"| {e['slot']:02d} | `{e['bundle_filename']}` | `{e['source_path']}` | {e['bytes']} | `{e['sha256'][:16]}...` |")
    lines.append("| 38 | `38_SOURCE_FRESHNESS_POLICY.md` | (generated) | -- | -- |")
    lines.append("| 39 | `39_PROJECT_SOURCE_MANIFEST.json` | (generated) | -- | -- |")
    lines.append("| 40 | `40_OPEN_PR_IMPACT_LEDGER.md` | (generated) | -- | -- |")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--execution-base-sha", required=True)
    ap.add_argument("--open-pr-dir", required=True, help="dir containing OPEN_PRS_INITIAL.json and open-pr-<N>.json")
    ap.add_argument("--source-set", default="scripts/project_sources/source_set_v4.json")
    ap.add_argument("--pr-classifications", default="scripts/project_sources/pr_classifications.json")
    ap.add_argument("--output-dir", required=True)
    ap.add_argument("--generated-at", required=True, help="ISO-8601 UTC timestamp, e.g. 2026-07-28T00:00:00Z")
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve()
    output_dir = Path(args.output_dir).resolve()
    upload_dir = output_dir / "UPLOAD_FILES"
    upload_dir.mkdir(parents=True, exist_ok=True)

    source_set = json.loads((repo_root / args.source_set).read_text())
    classifications = json.loads((repo_root / args.pr_classifications).read_text())
    open_pr_dir = Path(args.open_pr_dir).resolve()
    prs = load_captured_prs(open_pr_dir)
    initial = json.loads((open_pr_dir / "OPEN_PRS_INITIAL.json").read_text())
    changed_file_counts = {}
    changed_counts_path = open_pr_dir / "OPEN_PRS_CHANGED_FILE_COUNTS.json"
    if changed_counts_path.exists():
        changed_file_counts = json.loads(changed_counts_path.read_text())

    if len(prs) != len(initial):
        raise SystemExit(f"FATAL: captured per-PR file count ({len(prs)}) != initial inventory count ({len(initial)})")

    copied_entries = build_copied_slots(repo_root, args.execution_base_sha, source_set, upload_dir)

    pr_entries = build_pr_ledger_entries(prs, classifications, changed_file_counts)
    material_count = sum(1 for e in pr_entries if e["classification"] in ("SOURCE_SET_CHANGES_IF_MERGED", "SOURCE_CONTENT_REFRESH_IF_MERGED"))
    disposition = "CURRENT_MAIN_VALID_PENDING_OPEN_PR_REFRESH" if material_count > 0 else "CURRENT_MAIN_VALID"

    freshness_text = FRESHNESS_POLICY_TEXT.format(packet_id=PACKET_ID, execution_base_sha=args.execution_base_sha)
    (upload_dir / "38_SOURCE_FRESHNESS_POLICY.md").write_text(freshness_text)

    ledger_text = render_ledger_md(pr_entries, args.execution_base_sha, args.generated_at)
    (upload_dir / "40_OPEN_PR_IMPACT_LEDGER.md").write_text(ledger_text)

    manifest = {
        "schema_version": "1.0.0",
        "package_id": PACKET_ID,
        "repository": REPO,
        "base_branch": "main",
        "execution_base_sha": args.execution_base_sha,
        "generated_at": args.generated_at,
        "package_disposition": disposition,
        "upload_file_count": 40,
        "material_open_pr_count": material_count,
        "regeneration_triggered_by_open_pr_merge": True,
        "files": [],
    }
    for e in copied_entries:
        manifest["files"].append(
            {
                "slot": e["slot"],
                "bundle_filename": e["bundle_filename"],
                "artifact_type": "copied_source",
                "source_path": e["source_path"],
                "source_commit_sha": e["source_commit_sha"],
                "source_blob_sha": e["source_blob_sha"],
                "sha256": e["sha256"],
                "bytes": e["bytes"],
                "authority_class": e["authority_class"],
                "freshness_class": e["freshness_class"],
                "generated": False,
                "current_main_only": True,
                "open_pr_content_included": False,
                "notes": e["notes"],
            }
        )
    for slot_num, fname in [(38, "38_SOURCE_FRESHNESS_POLICY.md"), (39, "39_PROJECT_SOURCE_MANIFEST.json"), (40, "40_OPEN_PR_IMPACT_LEDGER.md")]:
        is_self = fname == "39_PROJECT_SOURCE_MANIFEST.json"
        data = None if is_self else (upload_dir / fname).read_bytes()
        entry = {
            "slot": slot_num,
            "bundle_filename": fname,
            "artifact_type": "generated_package_metadata",
            "source_path": None,
            "source_commit_sha": None,
            "source_blob_sha": None,
            "sha256": None if is_self else sha256_bytes(data),
            "bytes": None if is_self else len(data),
            "authority_class": "generated_package_metadata",
            "freshness_class": "GENERATED_FOR_BASE_SHA",
            "generated": True,
            "current_main_only": False,
            "open_pr_content_included": (slot_num == 40),
            "notes": (
                ["Generated by this packet's build script; non-authoritative.",
                 "This entry's own sha256/bytes are intentionally null: a manifest cannot "
                 "correctly self-hash (writing the hash changes the file that produced it). "
                 "Per the packet's manifest-authentication rule, outer package identity is "
                 "provided by the ZIP sha256 sidecar, not by this internal self-reference."]
                if is_self else
                ["Generated by this packet's build script; non-authoritative."]
            ),
        }
        manifest["files"].append(entry)

    manifest_json_final = json.dumps(manifest, indent=2, sort_keys=False) + "\n"
    (upload_dir / "39_PROJECT_SOURCE_MANIFEST.json").write_text(manifest_json_final)

    (output_dir / "SOURCE_RESOLUTION_REPORT.md").write_text(render_source_resolution_report(copied_entries))
    (output_dir / "SOURCE_REJECTION_LEDGER.md").write_text(render_rejection_ledger(copied_entries))
    (output_dir / "CURRENT_MAIN_40.md").write_text(render_current_main_40(copied_entries, args.execution_base_sha))

    open_pr_capture_dir = output_dir / "OPEN_PR_CAPTURE"
    open_pr_capture_dir.mkdir(exist_ok=True)
    for pr in prs:
        (open_pr_capture_dir / f"open-pr-{pr['number']}.json").write_text(json.dumps(pr, indent=2, sort_keys=True) + "\n")

    readme = f"""# {PACKET_ID}

Deterministic ChatGPT Project 40-source upload set for `{REPO}`, bound to
`execution_base_sha` `{args.execution_base_sha}`.

- `UPLOAD_FILES/` -- exactly 40 files; upload these to the ChatGPT Project as
  its source set. See `01_AGENTS.md` through `40_OPEN_PR_IMPACT_LEDGER.md`.
- `SOURCE_RESOLUTION_REPORT.md` -- per-slot selection evidence.
- `SOURCE_REJECTION_LEDGER.md` -- every removed/rejected candidate, classified.
- `CURRENT_MAIN_40.md` -- flat index of all 40 slots with hashes.
- `PACKAGE_VALIDATION.json` -- validation gate results for this build.
- `OPEN_PR_CAPTURE/` -- raw captured evidence for every open PR at build time.

Package disposition: `{disposition}`.

No ChatGPT Project upload or mutation was performed by generating this package.
"""
    (output_dir / "README.md").write_text(readme)

    print(json.dumps({"disposition": disposition, "material_open_pr_count": material_count, "upload_file_count": len(list(upload_dir.iterdir()))}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
