"""
Private Helper Primitives

Internal helpers extracted from ``dopemux.cli`` so command modules can
reuse them without importing the top-level CLI module. These cover
routing/env persistence, role-profile materialization, LiteLLM model
selection, CCR override generation, MetaMCP role sync, and the version
flag callback.
"""

import os
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence

import click
import yaml

from .. import __version__
from ..console import console
from ..profile_manager import ProfileManager


ROLE_SERVER_SERVICE_MAP = {
    "dopemux-conport": "dopemux-conport",
    "dopemux-serena": "dopemux-serena",
    "dopemux-zen": "dopemux-zen",
    "dopemux-pal": "dopemux-pal",
    "dopemux-gpt-researcher": "dopemux-gpt-researcher",
    "dopemux-desktop-commander": "dopemux-desktop-commander",
    "dopemux-leantime-bridge": "dopemux-leantime-bridge",
    "dopemux-claude-context": "dopemux-claude-context",
}

ATTENTION_PROFILE_DEFAULTS = {
    "scattered": {
        "session_duration_minutes": 20,
        "energy_preference": "low",
        "attention_mode": "scattered",
    },
    "focused": {
        "session_duration_minutes": 50,
        "energy_preference": "medium",
        "attention_mode": "focused",
    },
    "hyperfocus": {
        "session_duration_minutes": 90,
        "energy_preference": "high",
        "attention_mode": "hyperfocused",
    },
    "variable": {
        "session_duration_minutes": 45,
        "energy_preference": "any",
        "attention_mode": "any",
    },
}


def _get_routing_allowlist() -> set[str]:
    """Return the set of environment variable names allowed for export."""
    return {
        # Dopemux Identity
        "DOPEMUX_INSTANCE_ID",
        "DOPEMUX_WORKSPACE_ID",
        "DOPEMUX_CLAUDE_VIA_LITELLM",
        "DOPEMUX_DEFAULT_LITELLM",
        # Anthropic / LiteLLM Auth
        "ANTHROPIC_BASE_URL",
        "ANTHROPIC_API_BASE",
        "ANTHROPIC_API_KEY",
        "LITELLM_MASTER_KEY",
        "DOPEMUX_LITELLM_MASTER_KEY",
        # Database (if needed for metrics)
        "DOPEMUX_LITELLM_DB_URL",
        "LITELLM_DATABASE_URL",
        "DATABASE_URL",
        # Claude Code Router (CCR)
        "CLAUDE_CODE_ROUTER_PORT",
        "CLAUDE_CODE_ROUTER_HOME",
        "CLAUDE_CODE_ROUTER_CONFIG",
        "CLAUDE_CODE_ROUTER_LOG",
        "CLAUDE_CODE_ROUTER_PROVIDER",
        "CLAUDE_CODE_ROUTER_MODELS",
        "CLAUDE_CODE_ROUTER_UPSTREAM_URL",
        "CLAUDE_CODE_ROUTER_UPSTREAM_KEY_VAR",
        "CLAUDE_CODE_ROUTER_UPSTREAM_KEY",
    }


def _persist_instance_env_exports(
    project_root: Path, instance_id: str, env_vars: Dict[str, str]
) -> None:
    """
    Persist instance environment variables for use outside Dopemux processes.

    Writes both `export`-style and `.env`-style files with a strict allowlist
    of routing and identity variables.
    """
    try:
        target_dir = project_root / ".dopemux" / "env"
        target_dir.mkdir(parents=True, exist_ok=True)

        slug = instance_id or "A"
        export_path = target_dir / f"instance_{slug}.sh"
        env_path = target_dir / f"instance_{slug}.env"

        allowlist = _get_routing_allowlist()
        export_secrets = os.environ.get("DOPEMUX_EXPORT_SECRETS") == "1"

        filtered_vars = {}
        for k, v in env_vars.items():
            if k not in allowlist:
                continue

            # Pattern-based secret detection
            is_secret = any(
                p in k for p in ("API_KEY", "TOKEN", "SECRET", "PASSWORD", "MASTER_KEY")
            )
            if is_secret and not export_secrets:
                continue

            filtered_vars[k] = v

        sorted_items = sorted(filtered_vars.items())

        with export_path.open("w", encoding="utf-8") as export_file:
            export_file.write("#!/usr/bin/env bash\n")
            export_file.write(
                "# Autogenerated by Dopemux – current instance environment\n"
            )
            export_file.write(
                "# Source this file in your shell to mirror Dopemux routing context.\n\n"
            )
            for key, value in sorted_items:
                value_str = "" if value is None else str(value)
                export_file.write(f"export {key}={shlex.quote(value_str)}\n")

        with env_path.open("w", encoding="utf-8") as env_file:
            env_file.write(
                "# Autogenerated by Dopemux – docker-compose compatible env file\n"
            )
            for key, value in sorted_items:
                value_str = "" if value is None else str(value)
                safe_value = value_str.replace("\\", "\\\\").replace('"', '\\"')
                env_file.write(f'{key}="{safe_value}"\n')

        # Refresh convenience pointers for the active instance
        shutil.copyfile(export_path, target_dir / "current.sh")
        shutil.copyfile(env_path, target_dir / "current.env")

        relative_export = export_path.relative_to(project_root)
        console.print(
            f"[text.dim]✓ Instance environment exported to {relative_export} "
            f"(source .dopemux/env/current.sh to mirror in this shell)[/text.dim]"
        )
    except Exception as exc:  # pragma: no cover - best effort persistence
        console.print(
            f"[warning]⚠️  Could not persist instance environment: {exc}[/warning]"
        )


def _ensure_role_profile(
    spec,
) -> Optional[object]:  # returns DopemuxProfile when available
    """Ensure a profile file exists for the given role spec."""

    profile_name = getattr(spec, "profile_name", None)
    if not profile_name:
        return None

    manager = ProfileManager()
    existing = manager.get_profile(profile_name)
    if existing:
        return existing

    profiles_dir = manager.profiles_dir
    profiles_dir.mkdir(parents=True, exist_ok=True)

    required = sorted({"conport", *(spec.required_servers or [])})
    optional = sorted(set(spec.optional_servers or []))

    attention_cfg = ATTENTION_PROFILE_DEFAULTS.get(
        spec.attention_state, ATTENTION_PROFILE_DEFAULTS["variable"]
    )

    profile_data = {
        "name": profile_name,
        "display_name": spec.label,
        "description": spec.description,
        "mcp_servers": {
            "required": required,
            "enabled": optional,
            "disabled": [],
        },
        "adhd_config": {
            "session_duration_minutes": attention_cfg["session_duration_minutes"],
            "energy_preference": attention_cfg["energy_preference"],
            "attention_mode": attention_cfg["attention_mode"],
        },
        "markers": {
            "required_files": [],
            "optional_files": [],
        },
    }

    profile_path = profiles_dir / f"{profile_name}.yaml"
    with open(profile_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(profile_data, f, sort_keys=False)

    return manager.get_profile(profile_name)


def _load_litellm_models(config_path: Path) -> List[str]:
    """Load model names from a LiteLLM YAML configuration file."""
    try:
        data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return []
    except yaml.YAMLError:
        return []

    models: List[str] = []
    for entry in data.get("model_list", []) if isinstance(data, dict) else []:
        if isinstance(entry, dict):
            name = entry.get("model_name")
            if isinstance(name, str) and name.strip():
                models.append(name.strip())
    return models


def _select_model_by_priority(
    models: Sequence[str], candidates: Sequence[str]
) -> Optional[str]:
    """Choose the first model matching any candidate (exact or substring) from a list."""
    if not models:
        return None

    normalized = [(model, model.lower()) for model in models]
    for candidate in candidates:
        candidate_lower = candidate.lower()
        for original, lower in normalized:
            if lower == candidate_lower:
                return original
        for original, lower in normalized:
            if candidate_lower in lower:
                return original

    return models[0]


def _build_router_overrides(
    provider_name: str, models: Sequence[str]
) -> Dict[str, str]:
    """Generate CCR router overrides based on available LiteLLM models."""
    overrides: Dict[str, str] = {}

    def _assign(key: str, candidates: Sequence[str]) -> None:
        chosen = _select_model_by_priority(models, candidates)
        if chosen:
            overrides[key] = f"{provider_name},{chosen}"

    _assign(
        "default",
        (
            "gpt-5",
            "gpt-5-pro",
            "openrouter-openai-gpt-5",
            "grok-4-fast",
            "grok-4",
            "grok-code-fast-1",
            "xai-grok-4-fast",
            "xai-grok-code-fast-1",
        ),
    )
    _assign(
        "background",
        (
            "grok-4-fast",
            "grok-code-fast-1",
            "xai-grok-4-fast",
            "xai-grok-code-fast-1",
            "openrouter-xai-grok-code-fast",
        ),
    )
    _assign(
        "think",
        (
            "gpt-5-codex",
            "openrouter-openai-gpt-5-codex",
            "codex",
        ),
    )
    _assign(
        "webSearch",
        (
            "gpt-5-mini",
            "openrouter-openai-gpt-5-mini",
            "glm-4.6",
            "grok-code-fast-1",
            "xai-grok-code-fast-1",
            "openrouter-google-gemini-2-flash",
        ),
    )

    return overrides


def _suggest_server_start(missing_servers: Iterable[str]) -> None:
    """Suggest commands to start missing MCP services."""

    services = sorted(
        {ROLE_SERVER_SERVICE_MAP.get(name, name) for name in missing_servers}
    )
    if not services:
        return
    service_arg = ",".join(services)
    console.print(
        f"[warning]💡 Start required services: dopemux mcp up --services {service_arg}[/warning]"
    )
    console.print(
        "[text.dim]   or bring up the full stack: dopemux mcp start-all --verify[/text.dim]"
    )


def _invoke_switch_role_script(role_key: str) -> None:
    if os.getenv("DOPEMUX_SKIP_SWITCH_ROLE_SCRIPT", "0").lower() in {
        "1",
        "true",
        "yes",
    }:
        return

    script_path = Path.home() / ".claude" / "switch-role.sh"
    if not script_path.exists():
        return

    try:
        subprocess.run([str(script_path), role_key], check=True)
        console.print(
            f"[text.dim]✓ Synced MetaMCP role via {script_path} {role_key}[/text.dim]"
        )
    except subprocess.CalledProcessError as exc:
        console.print(
            f"[warning]⚠ switch-role.sh failed (exit {exc.returncode}); continuing[/warning]"
        )


def show_version(ctx, param, value):
    """📜 Version Coordinates: Show version and exit."""
    if not value or ctx.resilient_parsing:
        return
    click.echo(f"Dopemux {__version__}")
    ctx.exit()
