from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class RuntimePaths:
    runner_script: Path
    repo_root: Path
    pricing_config_path: Path
    extraction_root: Path
    runs_root: Path
    latest_run_file: Path
    doctor_root: Path


PROMPT_HASH_MODE = "strict"
PROMPT_ROOT_ENV_VAR = "REPO_TRUTH_EXTRACTOR_PROMPT_ROOT"
LEGACY_PROMPT_ROOT_ENV_VAR = "UPGRADES_PROMPT_ROOT"
S_PROMPTS_MODE_ENV_VAR = "DOPEMUX_S_PROMPTS"
S_STEPS_ENV_VAR = "DOPEMUX_S_STEPS"
D0_MAX_FILES_ENV_VAR = "DOPEMUX_D0_MAX_FILES"
D1_MAX_FILES_ENV_VAR = "DOPEMUX_D1_MAX_FILES"
S_PROMPTS_AUTO = "auto"
S_PROMPTS_REGISTRY = "registry"
S_PROMPTS_LEGACY = "legacy"
S_PROMPTS_MODES = {S_PROMPTS_AUTO, S_PROMPTS_REGISTRY, S_PROMPTS_LEGACY}
PROOF_PACK_FILENAME = "PROOF_PACK.json"
COVERAGE_ROLLUP_FILENAME = "COVERAGE_ROLLUP.json"
CERTIFICATION_RESULT_FILENAME = "CERTIFICATION_RESULT.json"
STRICT_PASSTHROUGH_ATTESTATIONS_FILENAME = "STRICT_PASSTHROUGH_ATTESTATIONS.json"
RESUME_PROOF_FILENAME = "RESUME_PROOF.json"
RUN_LOG_FILENAME = "RUN.log"
TELEMETRY_DIRNAME = "telemetry"
RUN_DASHBOARD_FILENAME = "RUN_DASHBOARD.json"
STEP_METRICS_FILENAME = "STEP_METRICS.json"
FAILURE_INDEX_FILENAME = "FAILURE_INDEX.json"
COST_ABORT_FILENAME = "COST_ABORT.json"
COST_ABORT_REASON = "MAX_COST_USD_EXCEEDED"
RETRY_COST_REPORT_FILENAME = "RETRY_COST_REPORT.json"
TERMINAL_TIMELINE_FILENAME = "TERMINAL_TIMELINE.jsonl"
SPEND_LEDGER_FILENAME = "SPEND_LEDGER.json"
PROMPTSET_BLOCKED_REASON = "PROMPTSET_INVALID"
PROMPTSET_BLOCKED_EXIT_CODE = 2
PROMPTGEN_SCANNER_VERSION = "GX0_SCANNER_V1"
PROMPTGEN_INPUTS_FILENAME = "PROMPTGEN_INPUTS.json"
PROMPTGEN_FINGERPRINT_FILENAME = "PROJECT_FINGERPRINT.json"
PROMPTGEN_FAILED_FILENAME = "GX0_PROMPTGEN_SCAN.FAILED.json"
GEMINI_MODELS_FILENAME = "GEMINI_MODELS.json"
GEMINI_MODELS_FAILED_FILENAME = "GEMINI_MODELS.FAILED.json"
GEMINI_MODELS_SCHEMA_VERSION = "GEMINI_MODELS_V1"
GEMINI_MODELS_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models"
PARSE_RETRY_MAX_EXTRA_ATTEMPTS = 1
STRING_LITERAL_ERROR_SNIPPETS = (
    "unterminated string",
    "invalid \\escape",
    "invalid \\u",
    "invalid control character",
)
PROMPTGEN_DEFAULT_MAX_FILES = 600
PROMPTGEN_DEFAULT_MAX_BYTES = 300000
PROMPTGEN_DEFAULT_EXCERPT_BYTES = 4000
PROMPTGEN_DEFAULT_OUTPUT_DIR = "00_inputs"
PROMPTGEN_DEFAULT_INCLUDE_GLOBS = [
    "pyproject.toml",
    "dopemux.toml",
    "compose.yml",
    ".claude/**",
    ".dopemux/**",
    ".taskx/**",
    ".github/**",
    "config/**",
    "scripts/**",
    "tools/**",
    "compose/**",
    "docker/**",
    "AGENTS.md",
    "README.md",
    "QUICK_START.md",
    "INSTALL.md",
    "CHANGELOG.md",
]
PROMPTGEN_DEFAULT_EXCLUDE_GLOBS = [
    "**/.git/**",
    "**/.venv/**",
    "**/__pycache__/**",
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/.DS_Store",
    "**/*.png",
    "**/*.jpg",
    "**/*.jpeg",
    "**/*.webp",
    "**/*.gif",
    "**/*.pdf",
    "**/*.zip",
]
INTERACTIVE_SAFE_BATCH_WAIT_SECONDS = 1800
FIRST_LIVE_PRESET_NAME = "first-live"
STAGED_SAFE_PRESET_NAME = "staged-safe"
FIRST_LIVE_PRESET_DEFAULT_CAP_USD = 5.0
STAGED_SAFE_PRESET_DEFAULT_CAP_USD = 2.5
FIRST_LIVE_INITIAL_PHASES = ("A", "H", "D", "C")
FIRST_LIVE_POST_REVIEW_PHASES = ("R", "X", "T", "Z", "S", "SP")
PARSE_FAILURE_ABORT_THRESHOLD = 0.05
DPMX_ROUTING_ENABLE_ENV = "DPMX_ROUTING_ENABLE"
DPMX_MODEL_INVENTORY_ENV = "DPMX_MODEL_INVENTORY"
DPMX_MODEL_EXTRACT_ENV = "DPMX_MODEL_EXTRACT"
DPMX_MODEL_SYNTHESIS_ENV = "DPMX_MODEL_SYNTHESIS"
DPMX_MODEL_QA_ENV = "DPMX_MODEL_QA"
DPMX_BENCHMARK_ROUTE_OWNERSHIP_ENV = "DPMX_BENCHMARK_ROUTE_OWNERSHIP"
DPMX_EXPLICIT_STEP_ROUTES_ENV = "DPMX_EXPLICIT_STEP_ROUTES"
DPMX_WEBHOOK_URL_ENV = "DPMX_WEBHOOK_URL"
DPMX_WEBHOOK_SECRET_ENV = "DPMX_WEBHOOK_SECRET"
DPMX_WEBHOOK_TIMEOUT_SECONDS_ENV = "DPMX_WEBHOOK_TIMEOUT_SECONDS"
DPMX_WEBHOOK_REQUIRED_ENV = "DPMX_WEBHOOK_REQUIRED"
DPMX_WEBHOOK_AUTO_CONTINUE_ENV = "DPMX_WEBHOOK_AUTO_CONTINUE"
DPMX_LIVE_OK_ENV = "DPMX_LIVE_OK"
DPMX_WEBHOOK_SCHEMA = "DPMX_WEBHOOK_V1"
DPMX_WEBHOOK_EVENT = "batch.completed"
BENCHMARK_ROUTE_OWNERSHIP_MODE = "strict_extraction_lane_owned_v1"

CONFIG_FILE = Path(__file__).resolve()
RUNNER_SCRIPT = CONFIG_FILE.with_name("run_extraction_v5.py")
REPO_ROOT = CONFIG_FILE.parents[2]
PRICING_CONFIG_PATH = REPO_ROOT / "config" / "pricing.yaml"
V5_EXTRACTION_ROOT = Path("extraction/repo-truth-extractor/v5")
V5_RUNS_ROOT = V5_EXTRACTION_ROOT / "runs"
V5_LATEST_RUN_FILE = V5_EXTRACTION_ROOT / "latest_run_id.txt"
V5_DOCTOR_ROOT = V5_EXTRACTION_ROOT / "doctor"
RUNTIME_PATHS = RuntimePaths(
    runner_script=RUNNER_SCRIPT,
    repo_root=REPO_ROOT,
    pricing_config_path=PRICING_CONFIG_PATH,
    extraction_root=V5_EXTRACTION_ROOT,
    runs_root=V5_RUNS_ROOT,
    latest_run_file=V5_LATEST_RUN_FILE,
    doctor_root=V5_DOCTOR_ROOT,
)
