"""
Prometheus Monitoring & Metrics for DopeconBridge

Tracks 20+ metrics across all Phase 2 components:
- Event publishing latency
- Deduplication hit rates
- Aggregation reduction
- Pattern detection insights
- Circuit breaker states
- Agent event counts
- Cache performance

Features:
- Prometheus client integration
- Histogram, Counter, Gauge metrics
- Automatic metric collection hooks
- Grafana-compatible metric names
"""

import logging
import time
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from prometheus_client import CollectorRegistry

try:
    from prometheus_client import (
        Counter,
        Gauge,
        Histogram,
        Info,
        CollectorRegistry,
        generate_latest,
        CONTENT_TYPE_LATEST
    )
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False
    CollectorRegistry = None  # type: ignore
    logger = logging.getLogger(__name__)
    logger.warning("Prometheus client not available - metrics disabled")


logger = logging.getLogger(__name__)


class DopeconBridgeMetrics:
    """
    Centralized metrics collection for DopeconBridge.

    Tracks all Phase 2 components:
    - EventBus (publishing, deduplication)
    - Aggregation engine
    - Pattern detection
    - Circuit breakers
    - Agent integrations
    - Cache performance
    """

    def __init__(self, registry: Optional[CollectorRegistry] = None):
        """
        Initialize metrics.

        Args:
            registry: Optional Prometheus registry (creates new if None)
        """
        if not PROMETHEUS_AVAILABLE:
            self.enabled = False
            return

        self.enabled = True
        self.registry = registry or CollectorRegistry()

        # Event Publishing Metrics
        self.event_publish_latency = Histogram(
            'dopecon_bridge_event_publish_latency_seconds',
            'Latency for event publishing to EventBus',
            buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
            registry=self.registry
        )

        self.events_published_total = Counter(
            'dopecon_bridge_events_published_total',
            'Total events published to EventBus',
            ['source_agent', 'event_type'],
            registry=self.registry
        )

        # Deduplication Metrics
        self.dedup_checks_total = Counter(
            'dopecon_bridge_dedup_checks_total',
            'Total deduplication checks performed',
            registry=self.registry
        )

        self.dedup_hits_total = Counter(
            'dopecon_bridge_dedup_hits_total',
            'Total duplicate events detected',
            registry=self.registry
        )

        self.dedup_hit_rate = Gauge(
            'dopecon_bridge_dedup_hit_rate_percent',
            'Deduplication hit rate percentage',
            registry=self.registry
        )

        # Aggregation Metrics
        self.aggregation_events_in = Counter(
            'dopecon_bridge_aggregation_events_in_total',
            'Events before aggregation',
            registry=self.registry
        )

        self.aggregation_events_out = Counter(
            'dopecon_bridge_aggregation_events_out_total',
            'Events after aggregation',
            registry=self.registry
        )

        self.aggregation_reduction_rate = Gauge(
            'dopecon_bridge_aggregation_reduction_percent',
            'Event reduction rate from aggregation',
            registry=self.registry
        )

        # Pattern Detection Metrics
        self.pattern_insights_total = Counter(
            'dopecon_bridge_pattern_insights_total',
            'Total insights generated by pattern detection',
            ['pattern_name', 'severity'],
            registry=self.registry
        )

        self.pattern_detection_latency = Histogram(
            'dopecon_bridge_pattern_detection_latency_seconds',
            'Pattern detection cycle latency',
            buckets=[0.1, 0.5, 1.0, 5.0, 10.0, 30.0, 60.0],
            registry=self.registry
        )

        self.pattern_detection_runs_total = Counter(
            'dopecon_bridge_pattern_detection_runs_total',
            'Total pattern detection cycles',
            registry=self.registry
        )

        # Circuit Breaker Metrics
        self.circuit_breaker_state = Gauge(
            'dopecon_bridge_circuit_breaker_state',
            'Circuit breaker state (0=closed, 1=open, 2=half_open)',
            ['breaker_name'],
            registry=self.registry
        )

        self.circuit_breaker_failures_total = Counter(
            'dopecon_bridge_circuit_breaker_failures_total',
            'Total failures recorded by circuit breakers',
            ['breaker_name'],
            registry=self.registry
        )

        self.circuit_breaker_fallback_calls_total = Counter(
            'dopecon_bridge_circuit_breaker_fallback_calls_total',
            'Total fallback calls when circuit open',
            ['breaker_name'],
            registry=self.registry
        )

        # Agent Integration Metrics
        self.agent_events_total = Counter(
            'dopecon_bridge_agent_events_total',
            'Total events emitted per agent',
            ['agent_name', 'event_type'],
            registry=self.registry
        )

        self.agent_emission_errors_total = Counter(
            'dopecon_bridge_agent_emission_errors_total',
            'Total emission errors per agent',
            ['agent_name'],
            registry=self.registry
        )

        # Cache Metrics (Phase 3)
        self.cache_hits_total = Counter(
            'dopecon_bridge_cache_hits_total',
            'Cache hits per tier',
            ['tier'],  # memory, redis, database
            registry=self.registry
        )

        self.cache_misses_total = Counter(
            'dopecon_bridge_cache_misses_total',
            'Cache misses per tier',
            ['tier'],
            registry=self.registry
        )

        self.cache_hit_rate = Gauge(
            'dopecon_bridge_cache_hit_rate_percent',
            'Cache hit rate per tier',
            ['tier'],
            registry=self.registry
        )

        # System Metrics
        self.active_agents = Gauge(
            'dopecon_bridge_active_agents',
            'Number of active agents',
            registry=self.registry
        )

        self.event_stream_length = Gauge(
            'dopecon_bridge_event_stream_length',
            'Current length of event stream',
            registry=self.registry
        )

    # Metric Recording Methods

    def record_event_published(self, agent: str, event_type: str, latency_seconds: float):
        """Record event publication"""
        if not self.enabled:
            return

        self.event_publish_latency.observe(latency_seconds)
        self.events_published_total.labels(source_agent=agent, event_type=event_type).inc()

    def record_dedup_check(self, is_duplicate: bool):
        """Record deduplication check"""
        if not self.enabled:
            return

        self.dedup_checks_total.inc()
        if is_duplicate:
            self.dedup_hits_total.inc()

    def update_dedup_hit_rate(self, hit_rate_percent: float):
        """Update deduplication hit rate gauge"""
        if not self.enabled:
            return

        self.dedup_hit_rate.set(hit_rate_percent)

    def record_aggregation(self, events_in: int, events_out: int):
        """Record aggregation cycle"""
        if not self.enabled:
            return

        self.aggregation_events_in.inc(events_in)
        self.aggregation_events_out.inc(events_out)

        reduction = ((events_in - events_out) / events_in * 100) if events_in > 0 else 0
        self.aggregation_reduction_rate.set(reduction)

    def record_pattern_insight(self, pattern_name: str, severity: str):
        """Record pattern insight generated"""
        if not self.enabled:
            return

        self.pattern_insights_total.labels(
            pattern_name=pattern_name,
            severity=severity
        ).inc()

    def record_pattern_detection_cycle(self, latency_seconds: float):
        """Record pattern detection cycle"""
        if not self.enabled:
            return

        self.pattern_detection_latency.observe(latency_seconds)
        self.pattern_detection_runs_total.inc()

    def update_circuit_breaker_state(self, breaker_name: str, state: str):
        """
        Update circuit breaker state.

        Args:
            breaker_name: Name of circuit breaker
            state: State (closed/open/half_open)
        """
        if not self.enabled:
            return

        state_map = {"closed": 0, "open": 1, "half_open": 2}
        self.circuit_breaker_state.labels(breaker_name=breaker_name).set(
            state_map.get(state, 0)
        )

    def record_circuit_breaker_failure(self, breaker_name: str):
        """Record circuit breaker failure"""
        if not self.enabled:
            return

        self.circuit_breaker_failures_total.labels(breaker_name=breaker_name).inc()

    def record_circuit_breaker_fallback(self, breaker_name: str):
        """Record circuit breaker fallback call"""
        if not self.enabled:
            return

        self.circuit_breaker_fallback_calls_total.labels(breaker_name=breaker_name).inc()

    def record_agent_event(self, agent_name: str, event_type: str):
        """Record agent event emission"""
        if not self.enabled:
            return

        self.agent_events_total.labels(agent_name=agent_name, event_type=event_type).inc()

    def record_agent_emission_error(self, agent_name: str):
        """Record agent emission error"""
        if not self.enabled:
            return

        self.agent_emission_errors_total.labels(agent_name=agent_name).inc()

    def record_cache_access(self, tier: str, hit: bool):
        """
        Record cache access.

        Args:
            tier: Cache tier (memory/redis/database)
            hit: Whether it was a hit or miss
        """
        if not self.enabled:
            return

        if hit:
            self.cache_hits_total.labels(tier=tier).inc()
        else:
            self.cache_misses_total.labels(tier=tier).inc()

    def update_cache_hit_rate(self, tier: str, hit_rate_percent: float):
        """Update cache hit rate for tier"""
        if not self.enabled:
            return

        self.cache_hit_rate.labels(tier=tier).set(hit_rate_percent)

    def update_active_agents(self, count: int):
        """Update active agent count"""
        if not self.enabled:
            return

        self.active_agents.set(count)

    def update_event_stream_length(self, length: int):
        """Update event stream length"""
        if not self.enabled:
            return

        self.event_stream_length.set(length)

    def export_metrics(self) -> bytes:
        """
        Export metrics in Prometheus format.

        Returns:
            Metrics in Prometheus text format
        """
        if not self.enabled:
            return b""

        return generate_latest(self.registry)

    def get_content_type(self) -> str:
        """Get Prometheus content type for HTTP response"""
        return CONTENT_TYPE_LATEST if self.enabled else "text/plain"
