#!/usr/bin/env python3
"""
Build import_to_postgresql_age-compatible JSON bundles from ConPort snapshot exports.

Input:
- Snapshot manifest generated by scripts/export_conport_sqlite_snapshot.py

Output:
- One JSON bundle per exported DB, containing:
  decisions, progress_entries, custom_data, context_links, system_patterns,
  active_context, product_context
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def build_bundle_for_db(db_entry: dict[str, Any]) -> dict[str, Any]:
    export_dir = Path(db_entry["export_dir"])

    decisions = read_jsonl(export_dir / "decisions.jsonl")
    progress_entries = read_jsonl(export_dir / "progress_entries.jsonl")
    custom_data = read_jsonl(export_dir / "custom_data.jsonl")
    context_links = read_jsonl(export_dir / "context_links.jsonl")
    system_patterns = read_jsonl(export_dir / "system_patterns.jsonl")
    active_context_rows = read_jsonl(export_dir / "active_context.jsonl")
    product_context_rows = read_jsonl(export_dir / "product_context.jsonl")

    return {
        "metadata": {
            "source_snapshot_export_dir": db_entry["export_dir"],
            "source_db_path": db_entry["db_path"],
            "source_db_size_bytes": db_entry.get("db_size_bytes"),
            "rows_exported_total": db_entry.get("rows_exported_total", 0),
        },
        "decisions": decisions,
        "progress_entries": progress_entries,
        "custom_data": custom_data,
        "context_links": context_links,
        "system_patterns": system_patterns,
        "active_context": active_context_rows[-1] if active_context_rows else None,
        "product_context": product_context_rows[-1] if product_context_rows else None,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build importer-compatible JSON bundle(s) from snapshot manifest."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        required=True,
        help="Path to snapshot manifest.json",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Output directory for generated bundles (default: <manifest_dir>/import_bundles)",
    )
    args = parser.parse_args()

    manifest = read_json(args.manifest)
    out_dir = args.output_dir or (args.manifest.parent / "import_bundles")
    out_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for db_entry in manifest.get("databases", []):
        db_label = (
            db_entry["db_path"]
            .replace("/", "__")
            .replace(".", "_")
            .replace(":", "_")
        )
        out_path = out_dir / f"{db_label}__conport_import_bundle.json"
        bundle = build_bundle_for_db(db_entry)
        out_path.write_text(json.dumps(bundle, indent=2) + "\n", encoding="utf-8")
        generated.append(str(out_path))

    print(
        json.dumps(
            {
                "manifest": str(args.manifest),
                "output_dir": str(out_dir),
                "bundle_count": len(generated),
                "bundles": generated,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
