#!/bin/bash
# ADHD Tmux Auto-Setup
# Adds ADHD status and bindings to tmux configuration
#
# Usage:
#   ./adhd-tmux-setup.sh [options]
#
# Options:
#   --no-backup    Don't backup existing ~/.tmux.conf
#   --force        Overwrite existing ADHD config

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOPEMUX_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Defaults
DO_BACKUP=true
FORCE=false

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-backup) DO_BACKUP=false; shift ;;
        --force) FORCE=true; shift ;;
        *) shift ;;
    esac
done

echo "🎨 ADHD Tmux Auto-Setup"
echo "======================="
echo ""

# Backup existing config
if [ -f ~/.tmux.conf ] && [ "$DO_BACKUP" = true ]; then
    cp ~/.tmux.conf ~/.tmux.conf.backup.$(date +%Y%m%d%H%M%S)
    echo "✅ Backed up ~/.tmux.conf"
fi

# Check if already configured
if grep -q "ADHD Engine" ~/.tmux.conf 2>/dev/null && [ "$FORCE" != true ]; then
    echo "ℹ️  ADHD tmux config already exists. Use --force to overwrite."
    exit 0
fi

# Remove existing ADHD config if forcing
if [ "$FORCE" = true ] && [ -f ~/.tmux.conf ]; then
    sed -i '' '/# BEGIN ADHD Engine/,/# END ADHD Engine/d' ~/.tmux.conf 2>/dev/null || true
fi

# Install status script
mkdir -p ~/.dopemux
cat > ~/.dopemux/adhd-tmux-status.sh << 'SCRIPT'
#!/bin/bash
# ADHD Tmux Status
ADHD_ENGINE_URL="${ADHD_ENGINE_URL:-http://localhost:3333}"
STATE=$(curl -s --connect-timeout 1 --max-time 2 "${ADHD_ENGINE_URL}/api/v1/state?user_id=default" 2>/dev/null)
if [ -z "$STATE" ]; then
    echo "🔌"
    exit 0
fi
if command -v jq &> /dev/null; then
    ENERGY=$(echo "$STATE" | jq -r '.energy // "unknown"')
    ATTENTION=$(echo "$STATE" | jq -r '.attention // "unknown"')
else
    ENERGY="?"
    ATTENTION="?"
fi
case "$ENERGY" in
    "high")   E="⚡" ;;
    "medium") E="🔋" ;;
    "low")    E="🪫" ;;
    *)        E="❓" ;;
esac
case "$ATTENTION" in
    "hyperfocus")   A="🔥" ;;
    "focused")      A="🎯" ;;
    "distracted")   A="🌊" ;;
    "fatigued")     A="😴" ;;
    "overwhelmed")  A="😰" ;;
    *)              A="🧠" ;;
esac
echo "${E}${A}"
SCRIPT
chmod +x ~/.dopemux/adhd-tmux-status.sh
echo "✅ Installed ~/.dopemux/adhd-tmux-status.sh"

# Add ADHD config to tmux.conf
cat >> ~/.tmux.conf << 'TMUXCONF'

# BEGIN ADHD Engine Configuration
# Generated by adhd-tmux-setup.sh

# Status bar with ADHD state
set -g status-right '#(~/.dopemux/adhd-tmux-status.sh) | %H:%M'
set -g status-right-length 50
set -g status-interval 30

# ADHD key bindings (Prefix + key)
bind a display-popup -E -w 60 -h 20 "python3 ~/code/dopemux-mvp/services/adhd_engine/cli/adhd.py status"
bind A display-popup -E -w 60 -h 20 "python3 ~/code/dopemux-mvp/services/adhd_engine/cli/adhd.py check"
bind b display-popup -E -w 40 -h 10 "python3 ~/code/dopemux-mvp/services/adhd_engine/cli/adhd.py break"

# END ADHD Engine Configuration
TMUXCONF
echo "✅ Added ADHD config to ~/.tmux.conf"

# Reload if tmux is running
if command -v tmux &> /dev/null && tmux list-sessions &> /dev/null; then
    tmux source-file ~/.tmux.conf 2>/dev/null || true
    echo "✅ Tmux configuration reloaded"
fi

echo ""
echo "🎉 Done! Tmux bindings:"
echo "   Prefix + a  →  Show ADHD status"
echo "   Prefix + A  →  Run all checks"
echo "   Prefix + b  →  Take a break"
