"""Portable ConPort wiring for project-level Claude config and git hooks."""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Optional, Sequence


def _run_git(args: Sequence[str], cwd: Path) -> Optional[str]:
    """Run a git command and return stripped stdout, or None on failure."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            check=True,
            capture_output=True,
            text=True,
        )
        output = result.stdout.strip()
        return output or None
    except Exception:
        return None


def detect_project_root(project: Optional[str] = None) -> Path:
    """Resolve project root from explicit path, git root, or current directory."""
    if project:
        return Path(project).expanduser().resolve()

    cwd = Path.cwd().resolve()
    git_root = _run_git(["rev-parse", "--show-toplevel"], cwd)
    if git_root:
        return Path(git_root).resolve()
    return cwd


def detect_workspace_id(project_root: Path, *, prefer_env: bool = True) -> str:
    """Resolve workspace id from env (optional), git root, or project root."""
    if prefer_env:
        workspace_id = os.getenv("DOPEMUX_WORKSPACE_ID")
        if workspace_id:
            return workspace_id

    git_root = _run_git(["rev-parse", "--show-toplevel"], project_root)
    if git_root:
        return str(Path(git_root).resolve())
    return str(project_root.resolve())


def detect_instance_id(project_root: Path, instance: Optional[str] = None) -> str:
    """Resolve instance id from explicit option, env, git branch, or folder name."""
    if instance:
        return instance

    env_instance = os.getenv("DOPEMUX_INSTANCE_ID")
    if env_instance:
        return env_instance

    branch = _run_git(["rev-parse", "--abbrev-ref", "HEAD"], project_root)
    if branch and branch != "HEAD":
        return branch

    return project_root.name


def _container_name(instance_id: str) -> str:
    if instance_id in {"", "main"}:
        return "mcp-conport"
    return f"mcp-conport_{instance_id}"


def wire_conport_project(project: Optional[str] = None, instance: Optional[str] = None) -> Path:
    """Write project `.claude/claude_config.json` with portable ConPort MCP wiring."""
    project_root = detect_project_root(project)
    instance_id = detect_instance_id(project_root, instance)
    # If project is explicit, prefer that workspace over inherited shell env.
    workspace_id = detect_workspace_id(project_root, prefer_env=project is None)

    claude_dir = project_root / ".claude"
    config_path = claude_dir / "claude_config.json"
    claude_dir.mkdir(parents=True, exist_ok=True)

    config = {}
    if config_path.exists():
        config = json.loads(config_path.read_text(encoding="utf-8"))

    mcp_servers = config.get("mcpServers")
    if not isinstance(mcp_servers, dict):
        mcp_servers = {}

    mcp_servers["conport"] = {
        "type": "stdio",
        "command": "docker",
        "args": [
            "exec",
            "-i",
            "-e",
            "DOPEMUX_INSTANCE_ID",
            "-e",
            "DOPEMUX_WORKSPACE_ID",
            _container_name(instance_id),
            "uvx",
            "--from",
            "context-portal-mcp",
            "conport-mcp",
        ],
        "env": {
            "DOPEMUX_INSTANCE_ID": instance_id,
            "DOPEMUX_WORKSPACE_ID": workspace_id,
        },
    }
    config["mcpServers"] = mcp_servers

    config_path.write_text(f"{json.dumps(config, indent=2)}\n", encoding="utf-8")
    return config_path


def build_post_checkout_hook_content() -> str:
    """Generate portable post-checkout hook content."""
    return """#!/usr/bin/env bash
# Auto-generated by dopemux init for ConPort worktree wiring.

if ! command -v dopemux >/dev/null 2>&1; then
  exit 0
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
INSTANCE_ID="${DOPEMUX_INSTANCE_ID:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || basename "$REPO_ROOT")}"
if [ "$INSTANCE_ID" = "HEAD" ] || [ -z "$INSTANCE_ID" ]; then
  INSTANCE_ID="$(basename "$REPO_ROOT")"
fi

# Never block checkouts on wiring failures.
dopemux wire-conport --instance "$INSTANCE_ID" --project "$REPO_ROOT" >/dev/null 2>&1 || true
"""


def _resolve_hooks_dir(workspace: Path) -> Path:
    git_path = workspace / ".git"
    if git_path.is_dir():
        return git_path / "hooks"

    if git_path.is_file():
        raw = git_path.read_text(encoding="utf-8").strip()
        if raw.startswith("gitdir:"):
            git_dir = raw.split(":", 1)[1].strip()
            git_dir_path = Path(git_dir)
            if not git_dir_path.is_absolute():
                git_dir_path = (workspace / git_dir_path).resolve()
            return git_dir_path / "hooks"

    raise FileNotFoundError(f"No git metadata found under {workspace}")


def install_post_checkout_hook(workspace: Path) -> Path:
    """Install/update `.git/hooks/post-checkout` with portable wiring logic."""
    hooks_dir = _resolve_hooks_dir(workspace)
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_path = hooks_dir / "post-checkout"
    hook_path.write_text(build_post_checkout_hook_content(), encoding="utf-8")
    hook_path.chmod(0o755)
    return hook_path
