"""
Shell Hook Installer for Dopemux

Safely installs shell hooks for Claude Code monitoring.
Supports bash, zsh, and fish shells with backup and rollback capabilities.
"""

import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple
import re
import shutil
from datetime import datetime

class ShellHookInstaller:
    """
    Installer for Dopemux shell hooks with safety and rollback features.
    """

    def __init__(self):
        self.shell_configs = {
            'bash': ['~/.bashrc', '~/.bash_profile'],
            'zsh': ['~/.zshrc'],
            'fish': ['~/.config/fish/config.fish']
        }
        self.backup_suffix = '.dopemux_backup'

    def detect_shell(self) -> str:
        """Detect the current shell type."""
        shell_path = os.environ.get('SHELL', '')
        if 'zsh' in shell_path:
            return 'zsh'
        elif 'bash' in shell_path:
            return 'bash'
        elif 'fish' in shell_path:
            return 'fish'
        else:
            # Fallback detection
            if os.path.exists(os.path.expanduser('~/.zshrc')):
                return 'zsh'
            elif os.path.exists(os.path.expanduser('~/.bashrc')):
                return 'bash'
            else:
                return 'bash'  # Default fallback

    def get_shell_config_paths(self, shell_type: Optional[str] = None) -> List[Path]:
        """Get shell configuration file paths."""
        if shell_type is None:
            shell_type = self.detect_shell()

        config_files = self.shell_configs.get(shell_type, [])
        return [Path(os.path.expanduser(path)) for path in config_files]

    def check_existing_hooks(self, config_path: Path) -> bool:
        """Check if Dopemux hooks are already installed."""
        if not config_path.exists():
            return False

        content = config_path.read_text()
        return 'dopemux_trigger' in content or 'dopemux hooks' in content

    def create_backup(self, config_path: Path) -> Path:
        """Create a backup of the shell config file."""
        backup_path = config_path.with_suffix(f'{config_path.suffix}{self.backup_suffix}')
        shutil.copy2(config_path, backup_path)
        return backup_path

    def restore_backup(self, config_path: Path) -> bool:
        """Restore from backup."""
        backup_path = config_path.with_suffix(f'{config_path.suffix}{self.backup_suffix}')
        if backup_path.exists():
            shutil.copy2(backup_path, config_path)
            backup_path.unlink()  # Remove backup after restore
            return True
        return False

    def generate_hook_content(self, shell_type: str) -> str:
        """Generate shell hook content for the detected shell."""
        from .claude_code_hooks import get_shell_hook_scripts

        scripts = get_shell_hook_scripts()

        if shell_type == 'zsh':
            return scripts['zsh_hooks']
        elif shell_type == 'fish':
            # Fish shell syntax (would need separate implementation)
            return "# Fish shell hooks not yet implemented\n"
        else:  # bash and default
            return scripts['bash_preexec'] + '\n\n' + scripts['bash_precmd']

    def install_hooks(self, shell_type: Optional[str] = None, force: bool = False) -> Tuple[bool, str]:
        """
        Install Dopemux shell hooks.

        Args:
            shell_type: Shell type ('bash', 'zsh', 'fish') or auto-detect
            force: Force reinstallation even if already installed

        Returns:
            Tuple of (success, message)
        """
        if shell_type is None:
            shell_type = self.detect_shell()

        config_paths = self.get_shell_config_paths(shell_type)

        if not config_paths:
            return False, f"No configuration files found for shell: {shell_type}"

        installed_count = 0

        for config_path in config_paths:
            try:
                # Check if already installed
                if not force and self.check_existing_hooks(config_path):
                    continue

                # Create backup
                if config_path.exists():
                    backup_path = self.create_backup(config_path)
                    print(f"Created backup: {backup_path}")

                # Ensure config file exists
                config_path.parent.mkdir(parents=True, exist_ok=True)
                if not config_path.exists():
                    config_path.touch()

                # Generate and append hook content
                hook_content = self.generate_hook_content(shell_type)

                # Add header comment
                header = f"""
# Dopemux Shell Hooks - Installed {datetime.now().isoformat()}
# Auto-generated by Dopemux hook installer
# These hooks monitor Claude Code activity for workflow optimization
# To remove: dopemux hooks --uninstall-shell-hooks

"""

                with open(config_path, 'a', encoding='utf-8') as f:
                    f.write(header)
                    f.write(hook_content)
                    f.write('\n')

                installed_count += 1
                print(f"Installed hooks in: {config_path}")

            except Exception as e:
                return False, f"Failed to install hooks in {config_path}: {e}"

        if installed_count > 0:
            message = f"Successfully installed Dopemux shell hooks for {shell_type} in {installed_count} configuration file(s)."
            message += "\n\nTo activate: Restart your shell or run 'source ~/.bashrc' (or ~/.zshrc)"
            message += "\n\nTo test: Run a command with 'claude' in it and check dopemux logs"
            return True, message
        else:
            return False, "Hooks already installed. Use --force to reinstall."

    def uninstall_hooks(self, shell_type: Optional[str] = None) -> Tuple[bool, str]:
        """
        Uninstall Dopemux shell hooks by restoring backups.

        Args:
            shell_type: Shell type or auto-detect

        Returns:
            Tuple of (success, message)
        """
        if shell_type is None:
            shell_type = self.detect_shell()

        config_paths = self.get_shell_config_paths(shell_type)

        if not config_paths:
            return False, f"No configuration files found for shell: {shell_type}"

        restored_count = 0
        manual_removal_needed = []

        for config_path in config_paths:
            try:
                # Try to restore backup first
                if self.restore_backup(config_path):
                    restored_count += 1
                    print(f"Restored backup for: {config_path}")
                else:
                    # Manual removal needed
                    if config_path.exists():
                        content = config_path.read_text()
                        # Remove Dopemux hook sections
                        lines = content.split('\n')
                        filtered_lines = []
                        skip_section = False

                        for line in lines:
                            if '# Dopemux Shell Hooks' in line:
                                skip_section = True
                            elif skip_section and line.strip() == '':
                                continue
                            elif skip_section and ('# Dopemux' in line or 'dopemux_trigger' in line):
                                continue
                            elif skip_section and line.startswith('add-zsh-hook') and 'dopemux' in line:
                                continue
                            elif skip_section and line.startswith('trap') and 'dopemux' in line:
                                continue
                            else:
                                skip_section = False
                                filtered_lines.append(line)

                        # Write back cleaned content
                        config_path.write_text('\n'.join(filtered_lines))
                        manual_removal_needed.append(str(config_path))

            except Exception as e:
                return False, f"Failed to uninstall hooks from {config_path}: {e}"

        if restored_count > 0:
            message = f"Successfully uninstalled hooks from {restored_count} configuration file(s) using backups."
        else:
            message = "Hooks removed from configuration files."

        if manual_removal_needed:
            message += f"\n\nManual cleanup may be needed for: {', '.join(manual_removal_needed)}"

        message += "\n\nTo complete uninstallation: Restart your shell"
        return True, message

    def list_backups(self, shell_type: Optional[str] = None) -> List[Path]:
        """List available backup files."""
        if shell_type is None:
            shell_type = self.detect_shell()

        config_paths = self.get_shell_config_paths(shell_type)
        backups = []

        for config_path in config_paths:
            backup_path = config_path.with_suffix(f'{config_path.suffix}{self.backup_suffix}')
            if backup_path.exists():
                backups.append(backup_path)

        return backups


def install_shell_hooks(shell_type: Optional[str] = None, force: bool = False) -> Tuple[bool, str]:
    """Convenience function to install shell hooks."""
    installer = ShellHookInstaller()
    return installer.install_hooks(shell_type, force)


def uninstall_shell_hooks(shell_type: Optional[str] = None) -> Tuple[bool, str]:
    """Convenience function to uninstall shell hooks."""
    installer = ShellHookInstaller()
    return installer.uninstall_hooks(shell_type)