#!/bin/bash
# Dopemux Migration to Unified Architecture
# Consolidates fragmented Docker setup into single orchestration

set -e

echo "🎯 Dopemux Unified Migration Script"
echo "=====================================";

echo "⚠️  This will stop all current containers and migrate to unified architecture"
read -p "Continue? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Migration cancelled."
    exit 1
fi

# Create backup directory
BACKUP_DIR="./backup/migration-$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"

echo "📦 Creating backup of current configuration..."

# Backup current environment files
cp .env "$BACKUP_DIR/.env.backup" 2>/dev/null || echo "No .env found"
cp .env.conport "$BACKUP_DIR/.env.conport.backup" 2>/dev/null || echo "No .env.conport found"
cp .env.leantime "$BACKUP_DIR/.env.leantime.backup" 2>/dev/null || echo "No .env.leantime found"

# Backup current docker-compose files
find . -name "docker-compose*.yml" -exec cp {} "$BACKUP_DIR/" \;

echo "✅ Backup created in $BACKUP_DIR"

echo "🛑 Stopping all existing containers..."

# Stop all current dopemux containers
docker ps --filter "name=dopemux" --filter "name=mcp-" --filter "name=metamcp" -q | xargs -r docker stop
docker ps --filter "name=milvus" --filter "name=redis" --filter "name=leantime" -q | xargs -r docker stop

echo "🧹 Cleaning up old containers and networks..."

# Remove containers (but preserve volumes for data safety)
docker ps -a --filter "name=dopemux" --filter "name=mcp-" --filter "name=metamcp" -q | xargs -r docker rm
docker ps -a --filter "name=milvus" --filter "name=redis" --filter "name=leantime" -q | xargs -r docker rm

# Remove old networks
docker network ls --filter "name=mcp" --filter "name=dopemux" --filter "name=leantime" -q | xargs -r docker network rm 2>/dev/null || true

echo "📝 Setting up unified configuration..."

# Create scripts directory if it doesn't exist
mkdir -p ./scripts

# Copy unified environment configuration
if [ -f ".env.unified" ]; then
    echo "🔧 Copying unified environment configuration..."
    echo "# Generated by migration script on $(date)" > .env
    echo "# Backup of original .env saved to $BACKUP_DIR" >> .env
    echo "" >> .env
    cat .env.unified >> .env
    echo "✅ Unified .env created"
else
    echo "❌ .env.unified not found! Please ensure the unified configuration files exist."
    exit 1
fi

echo "🚀 Starting unified architecture..."

# Start the unified system
if docker-compose -f docker-compose.unified.yml up -d; then
    echo "✅ Unified architecture started successfully!"
else
    echo "❌ Failed to start unified architecture"
    echo "Check logs with: docker-compose -f docker-compose.unified.yml logs"
    exit 1
fi

echo "⏳ Waiting for services to start..."
sleep 10

echo "🔍 Checking service health..."

# Check critical services
CRITICAL_SERVICES=("dopemux-redis-primary" "dopemux-postgres-primary" "dopemux-mcp-context7" "dopemux-mcp-zen" "dopemux-mcp-conport")

for service in "${CRITICAL_SERVICES[@]}"; do
    if docker ps --filter "name=$service" --filter "status=running" | grep -q "$service"; then
        echo "✅ $service is running"
    else
        echo "⚠️  $service is not running properly"
    fi
done

echo ""
echo "🎉 Migration Complete!"
echo "======================="
echo ""
echo "🌐 Services are now available at:"
echo "  • Leantime (PM): http://localhost:8080"
echo "  • Redis Commander: http://localhost:8081"
echo "  • Minio Console: http://localhost:9001"
echo ""
echo "🔧 MCP Servers running on ports 3002-3016:"
echo "  • Context7: 3002"
echo "  • Zen: 3003"
echo "  • ConPort: 3004"
echo "  • Task Master: 3005"
echo "  • Serena: 3006"
echo "  • Claude Context: 3007"
echo "  • GPT-R MCP: 3009"
echo "  • Leantime Bridge: 3015"
echo "  • Integration Bridge: 3016"
echo ""
echo "📊 Check status: docker-compose -f docker-compose.unified.yml ps"
echo "📋 View logs: docker-compose -f docker-compose.unified.yml logs [service_name]"
echo "🛑 Stop all: docker-compose -f docker-compose.unified.yml down"
echo ""

# Check for any port conflicts
echo "🔍 Checking for port conflicts..."
if netstat -tuln 2>/dev/null | grep -E ":(3002|3003|3004|3005|3006|3007|3009|3015|3016|5432|6379|6380|8080|8081|9000|9001|19530)" | grep LISTEN; then
    echo "⚠️  Some ports might be in use by other services. Check above output."
else
    echo "✅ No obvious port conflicts detected"
fi

echo ""
echo "📚 ADHD-Optimized Next Steps:"
echo "1. Verify MCP servers with: claude mcp list"
echo "2. Check ConPort context: curl http://localhost:3004/health"
echo "3. Test Integration Bridge: curl http://localhost:3016/health"
echo ""
echo "💾 Your data backup is saved in: $BACKUP_DIR"