#!/usr/bin/env bash
set -euo pipefail

# Sync known MCP docker-compose env vars from repo .env (and current shell)
# Writes docker/mcp-servers/.env with only the keys we know/need.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
DEST_DIR="$ROOT_DIR/docker/mcp-servers"
DEST_FILE="$DEST_DIR/.env"

KNOWN_KEYS=(
  OPENAI_API_KEY
  XAI_API_KEY
  ANTHROPIC_API_KEY
  OPENROUTER_API_KEY
  GEMINI_API_KEY
  EXA_API_KEY
)

SRC_ENV_FILE="$ROOT_DIR/.env"
[ -f "$SRC_ENV_FILE" ] || SRC_ENV_FILE=""

# Load from .env if present into current shell
if [ -n "$SRC_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  set -a; . "$SRC_ENV_FILE"; set +a
fi

mkdir -p "$DEST_DIR"
{
  echo "# Auto-generated by scripts/sync_mcp_env.sh"
  echo "# Only known keys are included; edit as needed."
  for key in "${KNOWN_KEYS[@]}"; do
    val=$(eval echo "\${$key-}")
    if [ -n "$val" ]; then
      # Strip simple surrounding quotes
      v="$val"; v="${v%\"}"; v="${v#\"}"; v="${v%\'}"; v="${v#\'}"
      echo "$key=$v"
    else
      echo "# $key=   # not set"
    fi
  done
} > "$DEST_FILE"

echo "✅ Wrote $DEST_FILE"
