global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'workspace_id']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'

receivers:
  - name: 'default'
    # Add webhook/email/slack config here later

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'workspace_id', 'instance_id']
